export type ClientRedirect = {
  from: string | string[];
  to: string;
};

/**
 * Legacy redirects — targets must exist on the public allowlist only.
 */
export const redirects: ClientRedirect[] = [
  // Hubs
  { from: '/reading-order', to: '/getting-started' },
  { from: '/overview/reading-order', to: '/getting-started' },
  { from: '/overview/architecture', to: '/overview/how-it-works' },
  { from: '/overview/token-model', to: '/overview/how-it-works' },
  { from: '/overview/fee-flow', to: '/overview/how-it-works' },
  { from: '/architecture', to: '/overview/how-it-works' },
  { from: '/tokenomics', to: '/overview/how-it-works' },
  { from: '/product', to: '/getting-started' },
  { from: '/protocols', to: '/overview/how-it-works' },
  { from: '/compressions', to: '/getting-started' },
  { from: '/compressions/reading-order', to: '/getting-started' },

  // Account / wallet (internal docs)
  { from: '/account-context', to: '/getting-started' },
  { from: '/wallet-architecture', to: '/getting-started' },
  { from: '/ACCOUNT_MODEL', to: '/getting-started' },
  { from: '/4626-connection-methods', to: '/getting-started' },
  { from: '/connection-methods', to: '/getting-started' },
  { from: '/csw-eoa-owner-lane-verification', to: '/getting-started' },

  // Reference aliases
  { from: '/chains', to: '/reference/addresses' },
  { from: '/current-contract-inventory', to: '/reference/addresses' },
  { from: '/reference/current-contract-inventory', to: '/reference/addresses' },
  { from: '/reference/chains', to: '/reference/addresses' },
  { from: '/reference/erc4337-debugging', to: '/getting-started' },
  { from: '/coins-metadata', to: '/reference/glossary' },
  { from: '/token-image', to: '/reference/glossary' },
  { from: '/zora-payout-recipient-design', to: '/reference/glossary' },

  // Concepts & primitives → contracts
  { from: '/concepts', to: '/contracts' },
  { from: '/concepts/vault', to: '/contracts/core/creator-ovault' },
  { from: '/concepts/lottery', to: '/contracts/utilities/lottery-manager' },
  { from: '/concepts/auction', to: '/contracts/strategies/cca-launch' },
  { from: '/primitives', to: '/contracts' },
  { from: '/primitives/market/vault', to: '/contracts/core/creator-ovault' },
  { from: '/primitives/market/auction', to: '/contracts/strategies/cca-launch' },
  { from: '/primitives/game-loop/lottery', to: '/contracts/utilities/lottery-manager' },
  {
    from: '/primitives/game-loop/lottery-amoe-test-matrix',
    to: '/contracts/utilities/lottery-manager',
  },

  // Guides & app surfaces
  { from: '/creator-workspace', to: '/guides/launch-token' },
  { from: '/creator-workspace-implementation-plan', to: '/guides/launch-token' },
  { from: '/frontend/creator-workspace', to: '/guides/launch-token' },
  { from: '/frontend/creator-workspace-implementation-plan', to: '/guides/launch-token' },
  { from: '/users/explore-analytics', to: '/getting-started' },
  { from: '/guides/troubleshooting', to: '/getting-started' },
  { from: '/guides/troubleshooting/activate-account-signing', to: '/getting-started' },
  { from: '/guides/troubleshooting/userop-signature-errors', to: '/getting-started' },
  { from: '/guides/troubleshooting/delayed-completion', to: '/getting-started' },

  // Operators & engineering (repo-only)
  { from: '/operators', to: '/getting-started' },
  { from: '/publishing', to: '/getting-started' },
  { from: '/PUBLISHING', to: '/getting-started' },
  { from: '/developers/api-reference', to: '/contracts' },
  { from: '/api', to: '/contracts' },
  { from: '/api/index', to: '/contracts' },
  { from: '/uniswap-ai-overview', to: '/contracts' },
  { from: '/agent-skills', to: '/getting-started' },
  { from: '/agent-workflow', to: '/getting-started' },
  {
    from: '/superpowers/specs/2026-04-06-waitlist-allowlist-separation-design',
    to: '/getting-started',
  },

  // Trust → audits hub (Fable) or contracts
  { from: '/security', to: '/contracts' },
  { from: '/security-scan-overview', to: '/audits/fable' },
  { from: '/security/agent-security-model', to: '/contracts' },
  { from: '/security/mutable-surface-inventory', to: '/contracts' },
  { from: '/audits/README', to: '/audits' },
  { from: '/audits/x-ray/contract-audit-pass-2026-06', to: '/audits/fable/full-repo-review-2026-06' },
  { from: '/audits/github-supply-chain-setup', to: '/audits/fable' },
  { from: '/audits/internal-monorepo-audit-2026-03-30', to: '/audits/fable' },
  { from: '/audits/npm-advisories-triage', to: '/audits/fable' },
  { from: '/audits/production-parity-checklist', to: '/audits/fable' },
  { from: '/ajna-erc4626-kpr-adversarial-audit', to: '/contracts' },
  { from: '/ajna-erc4626-kpr-executive-brief', to: '/contracts' },
  { from: '/ajna-erc4626-kpr-master-qna', to: '/contracts' },
  {
    from: '/charm-alpha-vaults-v2-4626fun-adversarial-audit',
    to: '/contracts',
  },
  {
    from: '/charm-alpha-vaults-v2-4626fun-executive-brief',
    to: '/contracts',
  },
  { from: '/charm-alpha-vaults-v2-4626fun-master-qa', to: '/contracts' },
  { from: '/codex-security-findings', to: '/contracts' },
  { from: '/codex-security-second-pass-review', to: '/contracts' },
  { from: '/breakout-report', to: '/contracts' },
  { from: '/deep-research-report', to: '/contracts' },
  { from: ['/deep-research-report-1', '/deep-research-report-(1)'], to: '/contracts' },
  { from: ['/deep-research-report-2', '/deep-research-report-(2)'], to: '/contracts' },

  // Operations → addresses or deploy guides
  { from: '/operations', to: '/reference/addresses' },
  { from: '/operations/deployment', to: '/guides/launch-token' },
  { from: '/operations/deployment/releases', to: '/reference/addresses' },
  { from: '/operations/deployment/releases/current', to: '/reference/addresses' },
  { from: '/operations/deployment/pre-launch', to: '/guides/launch-token' },
  { from: '/operations/deployment/eliza-runtime', to: '/getting-started' },
  { from: '/operations/deployment/multisig/guide', to: '/reference/addresses' },
  { from: '/operations/vault/greenfield-launch-readiness', to: '/guides/greenfield-checklist' },
  { from: '/operations/greenfield-launch-readiness', to: '/guides/greenfield-checklist' },
  { from: '/greenfield', to: '/guides/greenfield-checklist' },
  { from: '/guides/greenfield', to: '/guides/greenfield-checklist' },
  { from: '/strategy-bundle', to: '/guides/strategy-bundle' },
  { from: '/launch-bundle', to: '/guides/strategy-bundle' },
  { from: '/operations/vault/creator-strategy-features', to: '/guides/strategy-bundle' },
  { from: '/creator-strategy-features', to: '/guides/strategy-bundle' },
  { from: '/operations/vault/oracle-post-deploy-qa', to: '/contracts/utilities/creator-oracle' },
  { from: '/operations/vault/impairment-side-pocket-lifecycle-drill', to: '/reference/impairment-v1-disclosures' },
  { from: '/operations/automation', to: '/getting-started' },
  { from: '/operations/automation/keeper-http-api', to: '/getting-started' },
  { from: '/operations/automation/keeper-job-coordination', to: '/getting-started' },
  { from: '/operations/automation/vercel-cron-production-fixes', to: '/getting-started' },
  { from: '/operations/wallet/csw-recovery-playbook', to: '/getting-started' },
  { from: '/operations/wallet/sponsored-canonical-swap-pattern', to: '/getting-started' },
  { from: '/operations/wallet/privy-wallet-lanes', to: '/getting-started' },
  { from: '/operations/wallet/relay-owner-mutation-kit-guide', to: '/getting-started' },
  { from: '/operations/solana/solana-share-mesh-lottery-policy', to: '/overview/solana-share-mesh' },
  { from: '/operations/solana/solana-bridge-naming-invariant', to: '/overview/solana-share-mesh' },
  { from: '/operations/solana/solana-share-mesh-creator-provisioning', to: '/overview/solana-share-mesh' },
  { from: '/operations/platform/supabase-setup', to: '/getting-started' },
  { from: '/operations/platform/domain-setup', to: '/getting-started' },
  { from: '/operations/platform/supabase-schema-condensation', to: '/getting-started' },
  { from: '/operations/messaging/telegram-canonical-link-preservation', to: '/getting-started' },
  { from: '/telegram-canonical-link-preservation', to: '/getting-started' },
  { from: '/solana-spoke-article', to: '/overview/solana-share-mesh' },
  { from: '/operations/deployment/releases/v1.11.0-protocol-contract-readiness', to: '/reference/addresses' },
  { from: '/operations/deployment/releases/v1.11.1-protocol-contract-readiness', to: '/reference/addresses' },
  { from: '/operations/deployment/releases/v1.12.0-bytecode-epoch', to: '/reference/addresses' },
  { from: '/operations/deployment/releases/v1.12.1-bytecode-epoch', to: '/reference/addresses' },
  { from: '/operations/deployment/releases/v1.13.0-bytecode-epoch', to: '/reference/addresses' },
  { from: '/operations/deployment/releases/v1.14.0-bytecode-epoch', to: '/reference/addresses' },
  { from: '/operations/deployment/releases/v1.14.1', to: '/reference/addresses' },

  // Flat legacy operation slugs
  { from: '/operations/keeper-http-api', to: '/getting-started' },
  { from: '/operations/vercel-cron-production-fixes', to: '/getting-started' },
  { from: '/operations/creator-strategy-features', to: '/guides/strategy-bundle' },
  { from: '/operations/solana-share-mesh-lottery-policy', to: '/overview/solana-share-mesh' },
  { from: '/operations/privy-wallet-lanes', to: '/getting-started' },
  { from: '/operations/relay-owner-mutation-kit-guide', to: '/getting-started' },
  { from: '/operations/sponsored-canonical-swap-pattern', to: '/getting-started' },
  { from: '/operations/domain-setup', to: '/getting-started' },
  { from: '/operations/supabase-setup', to: '/getting-started' },
  { from: '/csw-base-app-reconciliation', to: '/getting-started' },
  { from: '/owner-mutation-decision-2026-05', to: '/getting-started' },
  { from: '/zora-csw-indexer-cron-spec', to: '/getting-started' },
  { from: '/zora-csw-indexer-runbook', to: '/getting-started' },
  { from: '/railway-keepr-primary-checklist', to: '/getting-started' },
  { from: ['/zora/MONOREPO_ARCHITECTURE', '/zora/monorepo_architecture'], to: '/overview/how-it-works' },
  { from: ['/zora/PROTOCOL_KNOWLEDGE', '/zora/protocol_knowledge'], to: '/overview/how-it-works' },
  { from: '/lens', to: '/overview/how-it-works' },
  { from: '/lens-grove', to: '/overview/how-it-works' },
  { from: '/farcaster-close-gap-phases', to: '/overview/how-it-works' },

  // Terminology / legacy product slugs (unique entries only)
  { from: '/solana-share-mesh', to: '/overview/solana-share-mesh' },
  { from: '/overview/solana', to: '/overview/solana-share-mesh' },
  { from: '/how-it-works', to: '/overview/how-it-works' },
];
