export type ClientRedirect = {
  from: string | string[];
  to: string;
};

/**
 * Legacy route redirects for docs.4626.fun.
 *
 * We intentionally keep this as an explicit map (vs pattern-based) so changes
 * are reviewable and predictable.
 *
 * Redirect targets should be canonical narrative-first routes.
 */
export const redirects: ClientRedirect[] = [
  // Docs reorg redirects (v1.7.1 epoch cleanup)
  { from: '/account-context', to: '/wallet-architecture' },
  { from: '/chains', to: '/reference/chains' },
  { from: '/coins-metadata', to: '/reference/glossary' },
  { from: '/current-contract-inventory', to: '/reference/current-contract-inventory' },
  { from: '/token-image', to: '/reference/glossary' },

  {
    from: '/telegram-canonical-link-preservation',
    to: '/operations/messaging/telegram-canonical-link-preservation',
  },

  // Operations folder reorg (2026-06) — flat root runbooks moved into lane subfolders
  { from: '/operations/keeper-http-api', to: '/operations/automation/keeper-http-api' },
  { from: '/operations/vercel-cron-production-fixes', to: '/operations/automation/vercel-cron-production-fixes' },
  { from: '/operations/control-plane-operator-cheatsheet', to: '/operations/automation/keeper-http-api' },
  { from: '/operations/control-plane-verification', to: '/operations/automation/keeper-http-api' },
  { from: '/operations/burn-stream-monitoring', to: '/operations/automation/keeper-http-api' },
  { from: '/operations/vault-strategy-reallocation', to: '/operations/automation/keeper-job-coordination' },
  { from: '/operations/owner-install-reference-methods', to: '/operations/wallet/relay-owner-mutation-kit-guide' },
  { from: '/operations/csw-recovery-playbook', to: '/operations/wallet/csw-recovery-playbook' },
  { from: '/operations/sponsored-canonical-swap-pattern', to: '/operations/wallet/sponsored-canonical-swap-pattern' },
  { from: '/operations/coinbase-smart-wallet-capabilities', to: '/operations/wallet/privy-wallet-lanes' },
  { from: '/operations/privy-wallet-lanes', to: '/operations/wallet/privy-wallet-lanes' },
  { from: '/operations/relay-owner-mutation-kit-guide', to: '/operations/wallet/relay-owner-mutation-kit-guide' },
  { from: '/operations/relay-sponsored-owner-mutation-flow', to: '/operations/wallet/relay-owner-mutation-kit-guide' },
  { from: '/operations/base-app-session-key-relay-part1-recipe', to: '/operations/wallet/relay-owner-mutation-kit-guide' },
  { from: '/operations/coinbase-inapp-signaturewrapper-bug', to: '/operators' },
  { from: '/operations/base-app-icon-refresh', to: '/operators' },
  { from: '/operations/greenfield-launch-readiness', to: '/operations/vault/greenfield-launch-readiness' },
  { from: '/operations/oracle-post-deploy-qa', to: '/operations/vault/oracle-post-deploy-qa' },
  { from: '/operations/creator-strategy-features', to: '/operations/vault/creator-strategy-features' },
  { from: '/operations/impairment-side-pocket-lifecycle-drill', to: '/operations/vault/impairment-side-pocket-lifecycle-drill' },
  { from: '/operations/creator-oVault-vault-gaps-v2', to: '/operations/vault/greenfield-launch-readiness' },
  { from: '/operations/ovault-module-immutability-and-recovery', to: '/operations/vault/greenfield-launch-readiness' },
  { from: '/operations/contract-size-gate', to: '/operations/vault/greenfield-launch-readiness' },
  { from: '/operations/ajna-vault-manager-p0-runbook', to: '/operations/vault/greenfield-launch-readiness' },
  { from: '/operations/yearn-inspired-p0-role-policy-apr-runbook', to: '/operations/vault/greenfield-launch-readiness' },
  { from: '/operations/solana-share-mesh-lottery-policy', to: '/operations/solana/solana-share-mesh-lottery-policy' },
  { from: '/operations/solana-share-mesh-budget-paths', to: '/operations/solana/solana-share-mesh-lottery-policy' },
  { from: '/operations/solana-share-mesh-creator-provisioning', to: '/operations/solana/solana-share-mesh-creator-provisioning' },
  { from: '/operations/solana-bridge-naming-invariant', to: '/operations/solana/solana-bridge-naming-invariant' },
  { from: '/operations/creator-share-hook-mainnet-upgrade', to: '/operations/solana/solana-share-mesh-lottery-policy' },
  { from: '/operations/akita-solana-share-mesh-audit', to: '/operators' },
  { from: '/operations/akita-full-stack-prelaunch', to: '/operators' },
  { from: '/operations/akita-keeper-stack-activation', to: '/operations/automation/keeper-http-api' },
  { from: '/operations/alfaclub-counter-trade-production-runbook', to: '/operators' },
  { from: '/operations/alfaclub-auth-hardening', to: '/operators' },
  { from: '/operations/alfaclub-creative-architecture', to: '/operators' },
  { from: '/operations/alfaclub-hermit-personalization', to: '/operators' },
  { from: '/operations/alfaclub-token-rotation', to: '/operators' },
  { from: '/operations/agent-lane-policy-matrix', to: '/operators' },
  { from: '/operations/hermit-pinata-agent-rebuild', to: '/operators' },
  { from: '/operations/virtuals-arena-railway-runbook', to: '/operators' },
  { from: '/operations/virtuals-arena-staging-checklist', to: '/operators' },
  { from: '/operations/virtuals-acp-bridge', to: '/operators' },
  { from: '/operations/acp-daily-market-news-automation', to: '/operators' },
  { from: '/operations/counter-trade-code-map', to: '/operators' },
  { from: '/operations/bot-registry', to: '/operators' },
  { from: '/operations/hermit-pinata-spanish', to: '/operators' },
  { from: '/operations/deployment/amoe-flag-rollout-plan', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/releases/v1.7.1-mainnet', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/releases/v1.7.1-post-broadcast-checklist', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/releases/v1.8.1-mainnet', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/releases/v1.8.1-pre-broadcast-checklist', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/releases/v1.8.2-mainnet', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/releases/v1.8.3-mainnet', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/releases/v1.10.1-mainnet', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/releases/v1.10.1-pre-broadcast-checklist', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/releases/v1.10.1-supabase-update-plan', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/releases/v1.10.1-vercel-env-plan', to: '/operations/deployment/releases' },
  { from: '/operations/explore-metrics-operations', to: '/users/explore-analytics' },
  { from: '/operations/dune-analytics-runbook', to: '/users/explore-analytics' },
  { from: '/operations/looker-studio-widget-recipe', to: '/users/explore-analytics' },
  { from: '/operations/ethos-canonical-score-cache', to: '/users/explore-analytics' },
  { from: '/operations/zora-profiles-refresh-runbook', to: '/users/explore-analytics' },
  { from: '/operations/ethos-chart-system-overview', to: '/users/explore-analytics' },
  { from: '/operations/ethos-chart-ops-guide', to: '/users/explore-analytics' },
  { from: '/operations/chart-query-review-2026', to: '/users/explore-analytics' },
  { from: '/operations/domain-setup', to: '/operations/platform/domain-setup' },
  { from: '/operations/supabase-setup', to: '/operations/platform/supabase-setup' },
  { from: '/operations/supabase-schema-condensation', to: '/operations/platform/supabase-schema-condensation' },
  { from: '/operations/supabase-zora-db-optimization', to: '/operations/platform/supabase-setup' },
  { from: '/operations/supabase-chart-optimization', to: '/operations/platform/supabase-setup' },
  { from: '/operations/dead-tables-analysis-2026-05', to: '/operations/platform/supabase-setup' },
  { from: '/operations/telegram-canonical-link-preservation', to: '/operations/messaging/telegram-canonical-link-preservation' },
  { from: '/operations/xmtp-browser-connect-canary', to: '/operations/deployment/eliza-runtime' },
  { from: '/operations/alfaclub-gmeow-outage-postmortem-2026-05-02', to: '/operators' },
  { from: '/operations/cre-keeper-rollout', to: '/operations/automation/keeper-http-api' },
  { from: '/operations/deployment/v1.10.1/deployment-instructions', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/v1.10.1/pre-broadcast-cleanup', to: '/operations/deployment/releases' },
  { from: '/operations/deployment/v1.10.1/post-broadcast-orphan-finalization', to: '/operations/deployment/releases' },

  {
    from: '/creator-workspace',
    to: '/frontend/creator-workspace',
  },
  {
    from: '/creator-workspace-implementation-plan',
    to: '/frontend/creator-workspace',
  },
  { from: '/frontend/creator-workspace-implementation-plan', to: '/frontend/creator-workspace' },
  { from: '/agent-skills', to: '/operators' },
  { from: '/agent-workflow', to: '/operators' },
  { from: '/operations/deployment/base-build', to: '/operations/deployment' },
  { from: '/operations/erc8004-agent-2205-discoverability', to: '/operations' },
  {
    from: '/superpowers/specs/2026-04-06-waitlist-allowlist-separation-design',
    to: '/developers/api-reference',
  },
  { from: '/audits/github-supply-chain-setup', to: '/audits' },
  { from: '/audits/internal-monorepo-audit-2026-03-30', to: '/audits' },
  { from: '/audits/npm-advisories-triage', to: '/audits' },
  { from: '/audits/production-parity-checklist', to: '/audits' },
  { from: '/compressions/reading-order', to: '/reading-order' },
  { from: '/operations/deployment/releases/v1.11.0-protocol-contract-readiness', to: '/operations/deployment/releases/current' },
  { from: '/operations/deployment/releases/v1.11.1-protocol-contract-readiness', to: '/operations/deployment/releases/current' },
  { from: '/operations/deployment/releases/v1.12.0-bytecode-epoch', to: '/operations/deployment/releases/current' },
  { from: '/operations/deployment/releases/v1.12.1-bytecode-epoch', to: '/operations/deployment/releases/current' },
  { from: '/operations/deployment/releases/v1.13.0-bytecode-epoch', to: '/operations/deployment/releases/current' },
  { from: '/operations/deployment/releases/v1.14.0-bytecode-epoch', to: '/operations/deployment/releases/current' },

  // Root docs moved to docs/_internal/ (2026-06 makeover)
  { from: '/zora-csw-indexer-cron-spec', to: '/operators' },
  { from: '/zora-csw-indexer-runbook', to: '/operators' },
  { from: '/csw-base-app-reconciliation', to: '/operations/wallet/csw-recovery-playbook' },
  { from: '/csw-eoa-owner-lane-verification', to: '/wallet-architecture' },
  { from: '/owner-mutation-decision-2026-05', to: '/operations/wallet/relay-owner-mutation-kit-guide' },
  { from: '/zora-payout-recipient-design', to: '/reference/glossary' },
  { from: '/uniswap-ai-overview', to: '/developers/api-reference' },
  { from: '/DEPLOY_SCHEMA_MIGRATION_RUNBOOK', to: '/operations/platform/supabase-schema-condensation' },
  { from: '/POST_MIGRATION_SMOKE_TEST_CHECKLIST', to: '/operators' },
  { from: '/SCHEMA_MIGRATION_VERIFICATION_REPORT', to: '/operators' },
  { from: '/railway-keepr-primary-checklist', to: '/operators' },
  { from: '/architecture', to: '/overview/architecture' },
  { from: '/product', to: '/guides' },
  { from: '/tokenomics', to: '/overview/fee-flow' },
  { from: '/protocols', to: '/overview/architecture' },
  { from: '/compressions', to: '/reading-order' },

  { from: '/api', to: '/developers/api-reference' },
  { from: '/api/index', to: '/developers/api-reference' },

  { from: '/overview/reading-order', to: '/reading-order' },
  { from: '/concepts', to: '/reference' },
  { from: '/concepts/vault', to: '/contracts/core/creator-ovault' },
  { from: '/concepts/lottery', to: '/contracts/utilities/lottery-manager' },
  { from: '/concepts/auction', to: '/contracts/strategies/cca-launch' },
  {
    from: '/primitives/game-loop/lottery-amoe-test-matrix',
    to: '/contracts/utilities/lottery-manager',
  },
  { from: '/primitives', to: '/reference' },
  { from: '/primitives/market/vault', to: '/contracts/core/creator-ovault' },
  { from: '/primitives/market/auction', to: '/contracts/strategies/cca-launch' },
  { from: '/primitives/game-loop/lottery', to: '/contracts/utilities/lottery-manager' },
  { from: ['/zora/MONOREPO_ARCHITECTURE', '/zora/monorepo_architecture'], to: '/overview/architecture' },
  { from: ['/zora/PROTOCOL_KNOWLEDGE', '/zora/protocol_knowledge'], to: '/overview/architecture' },

  { from: '/lens', to: '/overview/architecture' },
  { from: '/lens-grove', to: '/overview/architecture' },
  {
    from: '/farcaster-close-gap-phases',
    to: '/overview/architecture',
  },
  { from: '/solana-spoke-article', to: '/operations/solana/solana-share-mesh-lottery-policy' },

  { from: '/security-scan-overview', to: '/security' },

  { from: '/ajna-erc4626-kpr-adversarial-audit', to: '/audits/x-ray/contract-audit-pass-2026-06' },
  { from: '/ajna-erc4626-kpr-executive-brief', to: '/audits/x-ray/contract-audit-pass-2026-06' },
  { from: '/ajna-erc4626-kpr-master-qna', to: '/audits/x-ray/contract-audit-pass-2026-06' },
  {
    from: '/charm-alpha-vaults-v2-4626fun-adversarial-audit',
    to: '/audits/x-ray/contract-audit-pass-2026-06',
  },
  {
    from: '/charm-alpha-vaults-v2-4626fun-executive-brief',
    to: '/audits/x-ray/contract-audit-pass-2026-06',
  },
  { from: '/charm-alpha-vaults-v2-4626fun-master-qa', to: '/audits/x-ray/contract-audit-pass-2026-06' },
  { from: '/codex-security-findings', to: '/audits' },
  {
    from: '/codex-security-second-pass-review',
    to: '/audits',
  },
  { from: '/breakout-report', to: '/audits' },
  {
    from: '/deep-research-report',
    to: '/audits',
  },
  {
    from: ['/deep-research-report-1', '/deep-research-report-(1)'],
    to: '/audits',
  },
  {
    from: ['/deep-research-report-2', '/deep-research-report-(2)'],
    to: '/audits',
  },
];
