import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {buildOperationsSidebarItems} from './src/lib/operationsSidebar';

/**
 * Curated docs IA (2026-06): Start → Guides → Reference → Operators → Trust.
 * Autogenerated typedoc/forge API dumps are repo-only (`pnpm docs:refresh`).
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Start',
      collapsed: false,
      link: {type: 'doc', id: 'index'},
      items: [
        'overview/reading-order',
        'getting-started/index',
        'wallet-architecture',
        'ACCOUNT_MODEL',
        'connection-methods',
      ],
    },

    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      link: {type: 'doc', id: 'guides/index'},
      items: [
        'guides/launch-token',
        'guides/activate-vault',
        'users/explore-analytics',
        'frontend/creator-workspace',
        {
          type: 'category',
          label: 'Troubleshooting',
          collapsed: true,
          link: {type: 'doc', id: 'guides/troubleshooting/index'},
          items: [
            'guides/troubleshooting/activate-account-signing',
            'guides/troubleshooting/userop-signature-errors',
            'guides/troubleshooting/delayed-completion',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      link: {type: 'doc', id: 'reference/index'},
      items: [
        'reference/addresses',
        'reference/current-contract-inventory',
        'reference/glossary',
        'reference/chains',
        {
          type: 'category',
          label: 'Contracts',
          link: {type: 'doc', id: 'contracts/index'},
          items: [
            'contracts/core/creator-ovault',
            'contracts/core/creator-share-oft',
            'contracts/core/creator-ovault-wrapper',
            'contracts/governance/gauge-controller',
            'contracts/strategies/cca-launch',
            'contracts/utilities/lottery-manager',
          ],
        },
        'overview/architecture',
        'overview/token-model',
        'overview/fee-flow',
        'developers/api-reference',
        'reference/erc4337-debugging',
        'PUBLISHING',
      ],
    },

    {
      type: 'category',
      label: 'Operators',
      collapsed: true,
      link: {type: 'doc', id: 'operators/index'},
      items: buildOperationsSidebarItems(),
    },

    {
      type: 'category',
      label: 'Trust',
      collapsed: true,
      items: [
        'security/index',
        'security/agent-security-model',
        'security/mutable-surface-inventory',
        'audits/README',
        'audits/x-ray/contract-audit-pass-2026-06',
        'legal/terms',
        'legal/privacy',
      ],
    },
  ],
};

export default sidebars;
