import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for CreatorVault docs.
 * 
 * Uses autogenerated sidebars based on the docs/ folder structure.
 * The folder structure in 4626/docs/ determines the sidebar hierarchy.
 * 
 * Each _index.md file in a folder acts as the category landing page.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
