import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {buildApiReferenceSidebarItems} from './src/lib/apiSidebar';
import {buildOperationsSidebarItems} from './src/lib/operationsSidebar';

/**
 * Sidebar configuration for 4626 docs.
 *
 * Phase 2 IA: Start → Guides → Product → Build lanes → Trust → Reference.
 * Phase 3: Operations autogenerated; API on separate navbar sidebar (`api`).
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Start',
      collapsed: false,
      link: {type: 'doc', id: 'index'},
      items: [
        'overview/reading-order',
        'wallet-architecture',
        'ACCOUNT_MODEL',
        'connection-methods',
      ],
    },

    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      link: {type: 'doc', id: 'guides/index'},
      items: [
        {
          type: 'category',
          label: 'For holders',
          collapsed: false,
          items: ['getting-started/index', 'users/explore-analytics'],
        },
        {
          type: 'category',
          label: 'For creators',
          collapsed: true,
          items: [
            'guides/launch-token',
            'guides/activate-vault',
            'frontend/creator-workspace',
            {
              type: 'category',
              label: 'Featured Guidelines',
              items: [
                'guides/featured-guidelines/featured-checklist',
                'guides/featured-guidelines/product-guidelines',
                'guides/featured-guidelines/design-guidelines',
                'guides/featured-guidelines/technical-guidelines',
                'guides/featured-guidelines/notification-guidelines',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Troubleshooting',
          link: {type: 'doc', id: 'guides/troubleshooting/index'},
          items: [
            'guides/troubleshooting/compilation-status',
            'guides/troubleshooting/delayed-completion',
            'guides/troubleshooting/userop-signature-errors',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Product',
      collapsed: true,
      link: {type: 'doc', id: 'product/index'},
      items: [
        {
          type: 'category',
          label: 'Four Compressions',
          link: {type: 'doc', id: 'compressions/index'},
          items: [
            'compressions/deployment',
            'compressions/geography',
            'compressions/distribution',
            'compressions/engagement',
          ],
        },
        {
          type: 'category',
          label: 'Three Primitives',
          link: {type: 'doc', id: 'primitives/index'},
          items: [
            'primitives/account',
            {
              type: 'category',
              label: 'Market',
              link: {type: 'doc', id: 'primitives/market/index'},
              items: ['primitives/market/vault', 'primitives/market/auction'],
            },
            {
              type: 'category',
              label: 'Game Loop',
              link: {type: 'doc', id: 'primitives/game-loop/index'},
              items: ['primitives/game-loop/lottery'],
            },
          ],
        },
        'architecture/index',
        'tokenomics/index',
        'governance/index',
      ],
    },

    {
      type: 'category',
      label: 'Developers',
      collapsed: true,
      link: {type: 'doc', id: 'developers/index'},
      items: ['frontend/index', 'architecture/index'],
    },

    {
      type: 'category',
      label: 'Protocol Integrators',
      collapsed: true,
      link: {type: 'doc', id: 'protocols/index'},
      items: [
        {
          type: 'category',
          label: 'Integrations',
          link: {type: 'doc', id: 'integrations/index'},
          items: [
            'integrations/oft',
            'integrations/lens',
            'integrations/lens-grove',
          ],
        },
        {
          type: 'category',
          label: 'Contracts',
          link: {type: 'doc', id: 'contracts/index'},
          items: [
            {
              type: 'category',
              label: 'Core',
              link: {type: 'doc', id: 'contracts/core/index'},
              items: [
                'contracts/core/creator-registry',
                'contracts/core/creator-ovault',
                'contracts/core/creator-ovault-wrapper',
                'contracts/core/creator-share-oft',
              ],
            },
            {
              type: 'category',
              label: 'Governance',
              link: {type: 'doc', id: 'contracts/governance/index'},
              items: [
                'contracts/governance/gauge-controller',
                'contracts/governance/vault-gauge-voting',
                'contracts/governance/ve4626',
                'contracts/governance/voter-rewards-distributor',
              ],
            },
            {
              type: 'category',
              label: 'Strategies',
              link: {type: 'doc', id: 'contracts/strategies/index'},
              items: [
                'contracts/strategies/base-creator-strategy',
                'contracts/strategies/cca-launch',
              ],
            },
            {
              type: 'category',
              label: 'Utilities',
              link: {type: 'doc', id: 'contracts/utilities/index'},
              items: [
                'contracts/utilities/lottery-manager',
                'contracts/utilities/creator-oracle',
              ],
            },
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Operators/SRE',
      collapsed: true,
      link: {type: 'doc', id: 'operators/index'},
      items: buildOperationsSidebarItems(),
    },

    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      link: {type: 'doc', id: 'security/index'},
      items: [
        'security/agent-security-model',
        'security/agent-security-migration',
        'security/transactional-integrity-audit',
      ],
    },

    {
      type: 'category',
      label: 'Audits',
      collapsed: true,
      link: {type: 'doc', id: 'audits/README'},
      items: [
        {
          type: 'category',
          label: 'Ajna',
          items: ['audits/codex/audit_findings_factories_batchers_ajna'],
        },
        {
          type: 'category',
          label: 'Charm',
          items: ['audits/charm/index', 'audits/charm/executive-brief'],
        },
        {
          type: 'category',
          label: 'Codex',
          items: [
            'audits/codex/AUDIT_RECONCILIATION',
            'audits/codex/remediation-2026-04-02',
          ],
        },
        {
          type: 'category',
          label: 'Token Image',
          items: ['audits/token-image/index'],
        },
      ],
    },

    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      link: {type: 'doc', id: 'reference/index'},
      items: [
        'reference/addresses',
        'reference/glossary',
        'reference/chains',
        'reference/current-contract-inventory',
        'reference/diagram-style-guide',
        'reference/erc4337-debugging',
        'reference/coins-metadata',
        'reference/token-image',
        'reference/account-context',
        {
          type: 'category',
          label: 'Repository',
          items: [
            'reference/repo/index',
            'reference/repo/security',
            'reference/repo/deployments/index',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Legal',
      collapsed: true,
      link: {type: 'doc', id: 'legal/index'},
      items: ['legal/terms', 'legal/privacy'],
    },
  ],

  /** API reference — opened via navbar **API** tab (keeps Build sidebar readable). */
  api: buildApiReferenceSidebarItems(),
};

export default sidebars;
