#!/usr/bin/env bash
# Sync Shovel env from frontend/.env (no secret duplication in repo).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FRONTEND_ENV="${FRONTEND_ENV:-$ROOT/../../frontend/.env}"
OUT="$ROOT/.env"

if [[ ! -f "$FRONTEND_ENV" ]]; then
  echo "Missing frontend env: $FRONTEND_ENV" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$FRONTEND_ENV"
set +a

pick_logs_rpc() {
  local candidate url
  for candidate in "${BASE_LOGS_RPC_URL:-}" "${BASE_READ_RPC_URL:-}" "${BASE_RPC_URL:-}"; do
    url="$candidate"
    [[ -z "$url" ]] && continue
    if cast block-number --rpc-url "$url" >/dev/null 2>&1 \
      && cast logs --from-block 48345250 --to-block 48345255 \
        --address 0x02D7abC547F8B1e7E2D7a919D8D1005918361750 \
        --rpc-url "$url" >/dev/null 2>&1; then
      echo "$url"
      return
    fi
    echo "RPC probe failed: $(python3 -c "from urllib.parse import urlparse; print(urlparse('${url}').hostname or '?')")" >&2
  done
  echo "No working eth_getLogs RPC found in frontend/.env" >&2
  exit 1
}

LOGS_RPC="$(pick_logs_rpc)"
PG_URL="${DIRECT_URL:-${DATABASE_URL:-}}"

if [[ -z "$PG_URL" ]]; then
  echo "Set DIRECT_URL or DATABASE_URL in frontend/.env" >&2
  exit 1
fi
if [[ "$PG_URL" != *sslmode=* ]]; then
  PG_URL="${PG_URL}$( [[ "$PG_URL" == *'?'* ]] && echo '&' || echo '?' )sslmode=require"
fi
if [[ -z "$LOGS_RPC" ]]; then
  echo "Set BASE_LOGS_RPC_URL or BASE_RPC_URL in frontend/.env" >&2
  exit 1
fi

# v1.18.0 DeploymentBatcher first bytecode block (binary search on Base mainnet).
START_BLOCK="${SHOVEL_BASE_START_BLOCK:-48345250}"

cat >"$OUT" <<EOF
# Generated by scripts/sync-env-from-frontend.sh — do not commit.
SHOVEL_PG_URL=${PG_URL}
BASE_LOGS_RPC_URL=${LOGS_RPC}
BASE_RPC_URL=${BASE_RPC_URL:-}
DEPLOYMENT_BATCHER=${DEPLOYMENT_BATCHER:-0x02D7abC547F8B1e7E2D7a919D8D1005918361750}
LOTTERY_MANAGER=${LOTTERY_MANAGER:-0xbE87AD917bE7f6a9AE1F9c9dd0A7Ec7550F3F8C1}
SHOVEL_BASE_START_BLOCK=${START_BLOCK}
SHOVEL_BATCH_SIZE=${SHOVEL_BATCH_SIZE:-500}
SHOVEL_CONCURRENCY=${SHOVEL_CONCURRENCY:-1}
EOF

echo "Wrote $OUT (start block $START_BLOCK, RPC host: $(python3 -c "from urllib.parse import urlparse; print(urlparse('${LOGS_RPC}').hostname or '?')"))"
