#!/usr/bin/env bash
# Sync Shovel env from frontend/.env (no secret duplication in repo).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FRONTEND_ENV="${FRONTEND_ENV:-$ROOT/../../frontend/.env}"
OUT="$ROOT/.env"

if [[ ! -f "$FRONTEND_ENV" ]]; then
  echo "Missing frontend env: $FRONTEND_ENV" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$FRONTEND_ENV"
set +a

export SHOVEL_BASE_START_BLOCK="${SHOVEL_BASE_START_BLOCK:-48345250}"
export DEPLOYMENT_BATCHER="${DEPLOYMENT_BATCHER:-0x02D7abC547F8B1e7E2D7a919D8D1005918361750}"
export LOTTERY_MANAGER="${LOTTERY_MANAGER:-0xbE87AD917bE7f6a9AE1F9c9dd0A7Ec7550F3F8C1}"
export SHOVEL_PROBE_HEADER_BATCH="${SHOVEL_PROBE_HEADER_BATCH:-${SHOVEL_BATCH_SIZE:-200}}"

RPC_EXPORT="$(python3 "$ROOT/scripts/probe-shovel-rpc.py" --export)" || {
  echo "No working Shovel RPC found in frontend/.env (needs blockNumber + getLogs + header batch)" >&2
  exit 1
}
# shellcheck disable=SC1090
eval "$RPC_EXPORT"

PG_URL="${SHOVEL_PG_URL:-${DIRECT_URL:-${DATABASE_URL:-}}}"

# Optional direct db.* host when IPv4 reachable (pooler session URL is the fallback).
if [[ -z "${SHOVEL_PG_URL:-}" && -n "${SUPABASE_USE_DIRECT_PG:-}" && -n "${SUPABASE_URL:-}" && -n "${SUPABASE_DB_PASSWORD:-}" ]]; then
  REF="$(python3 - <<'PY'
import os, re
m = re.search(r"https://([^.]+)\\.supabase\\.co", os.environ.get("SUPABASE_URL", ""))
print(m.group(1) if m else "")
PY
)"
  if [[ -n "$REF" ]]; then
    PG_URL="postgresql://postgres:${SUPABASE_DB_PASSWORD}@db.${REF}.supabase.co:5432/postgres"
    echo "Using Supabase direct Postgres (db.${REF}.supabase.co) for Shovel" >&2
  fi
fi

if [[ -z "$PG_URL" ]]; then
  echo "Set DIRECT_URL, DATABASE_URL, or SUPABASE_URL+SUPABASE_DB_PASSWORD in frontend/.env" >&2
  exit 1
fi
if [[ "$PG_URL" != *sslmode=* ]]; then
  PG_URL="${PG_URL}$( [[ "$PG_URL" == *'?'* ]] && echo '&' || echo '?' )sslmode=require"
fi

START_BLOCK="${SHOVEL_BASE_START_BLOCK}"
BATCH_SIZE="${SHOVEL_BATCH_SIZE:-200}"
CONCURRENCY="${SHOVEL_CONCURRENCY:-1}"

cat >"$OUT" <<EOF
# Generated by scripts/sync-env-from-frontend.sh — do not commit.
SHOVEL_PG_URL=${PG_URL}
BASE_LOGS_RPC_URL=${BASE_LOGS_RPC_URL}
BASE_RPC_URL=${BASE_RPC_URL:-}
DEPLOYMENT_BATCHER=${DEPLOYMENT_BATCHER}
LOTTERY_MANAGER=${LOTTERY_MANAGER}
SHOVEL_BASE_START_BLOCK=${START_BLOCK}
SHOVEL_BATCH_SIZE=${BATCH_SIZE}
SHOVEL_CONCURRENCY=${CONCURRENCY}
EOF

echo "Wrote $OUT (start block $START_BLOCK, RPC host: $(python3 -c "from urllib.parse import urlparse; print(urlparse('${BASE_LOGS_RPC_URL}').hostname or '?')"), batch $BATCH_SIZE)"
