import { beforeEach, describe, expect, it, vi } from 'vitest'

import { createMockReq, createMockRes } from './helpers'

const mocks = vi.hoisted(() => ({
  guardAgentApiRequest: vi.fn(async () => ({ ok: true, ip: '127.0.0.1', auth: null })),
  checkRateLimit: vi.fn(() => ({ allowed: true, remaining: 19, resetAt: Date.now() + 60_000 })),
  getClientIp: vi.fn(() => '127.0.0.1'),
  rateLimitKey: vi.fn((...parts: string[]) => parts.join(':')),
  evaluateX402Payment: vi.fn(),
  sendPaymentRequiredResponse: vi.fn(),
  setSettlementResponseHeaders: vi.fn(),
  setX402CorsHeaders: vi.fn(),
  buildErc8004TechnicalReview: vi.fn(),
  tryUploadImmutableJson: vi.fn(),
}))

vi.mock('../../server/_lib/agent/agentApiGuard.js', () => ({
  guardAgentApiRequest: mocks.guardAgentApiRequest,
}))

vi.mock('../../server/_lib/x402Service.js', () => ({
  evaluateX402Payment: mocks.evaluateX402Payment,
  sendPaymentRequiredResponse: mocks.sendPaymentRequiredResponse,
  setSettlementResponseHeaders: mocks.setSettlementResponseHeaders,
  setX402CorsHeaders: mocks.setX402CorsHeaders,
}))

vi.mock('../../server/_lib/agent/erc8004Review.js', () => ({
  buildErc8004TechnicalReview: mocks.buildErc8004TechnicalReview,
}))

vi.mock('../../server/_lib/lensGrove.js', () => ({
  tryUploadImmutableJson: mocks.tryUploadImmutableJson,
}))

vi.mock('../../server/_lib/rateLimit.js', () => ({
  checkRateLimit: mocks.checkRateLimit,
  getClientIp: mocks.getClientIp,
  rateLimitKey: mocks.rateLimitKey,
  RATE_LIMITS: {
    agentFeedbackReview: { windowMs: 60_000, maxRequests: 20 },
  },
}))

const paidReview = {
  agentId: 2205,
  scanUrl: 'https://www.8004scan.io/agents/base/2205',
  identity: {
    ownerAddress: '0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18',
    agentWallet: '0xAb6d5C10b03300326CD7fAb7267Ae192842967b5',
    tokenUri: 'https://example.com/registration.json',
    rpcErrorCount: 0,
    agentRegistered: true,
    registryAddress: '0x8004A169FB4a3325136EB29fA0ceB6D2e539a432',
    chainId: 8453,
    links: {
      registry: 'https://basescan.org/address/0x8004A169FB4a3325136EB29fA0ceB6D2e539a432',
      token: 'https://basescan.org/token/0x8004A169FB4a3325136EB29fA0ceB6D2e539a432?a=2205',
      ownerAddress: 'https://basescan.org/address/0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18',
      agentWallet: 'https://basescan.org/address/0xAb6d5C10b03300326CD7fAb7267Ae192842967b5',
    },
  },
  registration: {
    source: 'provided',
    rawUrl: 'https://example.com/registration.json',
    finalUrl: 'https://example.com/registration.json',
    fetched: true,
    valid: true,
    name: 'Example Agent',
    serviceCount: 4,
    active: true,
    x402Support: true,
    payload: { name: 'Example Agent' },
    error: null,
  },
  endpoint: {
    source: 'registration',
    url: 'https://example.com/api',
    finalUrl: 'https://example.com/api',
    checked: true,
    ok: true,
    status: 200,
    responseTimeMs: 123,
    contentType: 'application/json',
    error: null,
  },
  reputation: {
    totalFeedback: 3,
    totalReviewers: 2,
    averageValue: '4',
    averageValueDecimals: 0,
    label: 'Strong',
  },
  checks: [
    { id: 'onchain-registration', passed: true, detail: 'ok' },
    { id: 'registration-payload', passed: true, detail: 'ok' },
  ],
  score: {
    value: '5',
    valueDecimals: 0,
    numericValue: 5,
    label: 'Excellent',
  },
  reasoning: 'Paid ERC-8004 review generated by 4626.',
  generatedAt: '2026-03-21T12:00:00.000Z',
  source: 'erc8004.paid.review.v1',
} as const

describe('v1/agents/feedback/review', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mocks.checkRateLimit.mockReturnValue({ allowed: true, remaining: 19, resetAt: Date.now() + 60_000 })
    mocks.guardAgentApiRequest.mockResolvedValue({ ok: true, ip: '127.0.0.1', auth: null })
    mocks.sendPaymentRequiredResponse.mockImplementation((_, res, params) =>
      res.status(402).json({
        x402Version: 1,
        error: params.error,
        accepts: [params.paymentRequirements],
      }))
    mocks.setSettlementResponseHeaders.mockImplementation((res, settlement) => {
      res.setHeader('payment-response', JSON.stringify(settlement))
    })
    mocks.tryUploadImmutableJson.mockResolvedValue({
      ok: true,
      result: {
        lensUri: 'lens://feedback-key',
        gatewayUrl: 'https://api.grove.storage/feedback-key',
        storageKey: 'feedback-key',
        statusUrl: null,
      },
    })
    mocks.buildErc8004TechnicalReview.mockResolvedValue(paidReview)
  })

  it('returns 429 when paid review rate limit is exceeded', async () => {
    mocks.checkRateLimit.mockReturnValueOnce({ allowed: false, remaining: 0, resetAt: Date.now() + 60_000 })
    const mod = await import('../_handlers/v1/agents/feedback/_review.ts')
    const req = createMockReq({ method: 'POST', body: { agentId: 2205 } })
    const res = createMockRes()

    await mod.default(req, res)

    expect(res.statusCode).toBe(429)
    expect(res.body?.error).toBe('Too many requests')
    expect(Number(res.getHeader('retry-after'))).toBeGreaterThan(0)
  })

  it('returns 400 when registrationUrl uses a non-http scheme', async () => {
    const mod = await import('../_handlers/v1/agents/feedback/_review.ts')
    const req = createMockReq({
      method: 'POST',
      body: { agentId: 2205, registrationUrl: 'javascript:alert(1)' },
    })
    const res = createMockRes()

    await mod.default(req, res)

    expect(res.statusCode).toBe(400)
    expect(res.body?.error).toBe('registrationUrl must be an http(s) URL.')
  })

  it('returns 402 when no payment header has been provided', async () => {
    mocks.evaluateX402Payment.mockResolvedValue({
      status: 'missing',
      paymentRequirements: {
        scheme: 'exact',
        network: 'base',
        maxAmountRequired: '1000000',
        resource: 'https://4626.fun/api/v1/agents/feedback/review',
        description: 'review',
        mimeType: 'application/json',
        payTo: '0xAb6d5C10b03300326CD7fAb7267Ae192842967b5',
        maxTimeoutSeconds: 300,
        asset: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
      },
      priceUsd: 1,
      network: 'base',
    })

    const mod = await import('../_handlers/v1/agents/feedback/_review.ts')
    const req = createMockReq({ method: 'POST', body: { agentId: 2205 } })
    const res = createMockRes()

    await mod.default(req, res)

    expect(res.statusCode).toBe(402)
    expect(mocks.sendPaymentRequiredResponse).toHaveBeenCalledOnce()
    expect(res.body.accepts?.[0]?.resource).toContain('/api/v1/agents/feedback/review')
  })

  it('returns the paid review packet, Grove payload, and unsigned calldata after settlement', async () => {
    mocks.evaluateX402Payment.mockResolvedValue({
      status: 'paid',
      paymentRequirements: {
        scheme: 'exact',
        network: 'base',
        maxAmountRequired: '1000000',
        resource: 'https://4626.fun/api/v1/agents/feedback/review',
        description: 'review',
        mimeType: 'application/json',
        payTo: '0xAb6d5C10b03300326CD7fAb7267Ae192842967b5',
        maxTimeoutSeconds: 300,
        asset: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
      },
      priceUsd: 1,
      network: 'base',
      payer: '0x1111111111111111111111111111111111111111',
      verification: {
        isValid: true,
        invalidReason: undefined,
        payer: '0x1111111111111111111111111111111111111111',
      },
      settlement: {
        success: true,
        transaction: '0xsettled',
        network: 'base',
        payer: '0x1111111111111111111111111111111111111111',
      },
    })

    const mod = await import('../_handlers/v1/agents/feedback/_review.ts')
    const req = createMockReq({
      method: 'POST',
      body: { agentId: 2205, registrationUrl: 'https://example.com/registration.json' },
    })
    const res = createMockRes()

    await mod.default(req, res)

    expect(res.statusCode).toBe(200)
    expect(mocks.setSettlementResponseHeaders).toHaveBeenCalledOnce()
    expect(res.body.success).toBe(true)
    expect(res.body.data.review.agentId).toBe(2205)
    expect(res.body.data.payment.protocol).toBe('x402')
    expect(res.body.data.feedback.feedbackURI).toBe('lens://feedback-key')
    expect(res.body.data.feedback.feedbackHash).toMatch(/^0x[a-f0-9]{64}$/)
    expect(res.body.data.feedback.calldata).toMatch(/^0x/)
    expect(res.body.data.feedback.payload.proofOfPayment.txHash).toBe('0xsettled')
  })
})
