import type {SidebarItemConfig} from '@docusaurus/plugin-content-docs';
import manifest from '../../api-sidebar-manifest.json';

type ApiSidebarManifest = {
  domains: Array<{id: string; label: string}>;
  routeMaps: Array<{id: string; label: string}>;
};

const {domains, routeMaps} = manifest as ApiSidebarManifest;

export function buildHttpHandlerSidebarItems(): SidebarItemConfig[] {
  const domainItems: SidebarItemConfig[] = domains.map((domain) => ({
    type: 'category',
    label: domain.label,
    collapsed: true,
    items: [
      {
        type: 'autogenerated',
        dirName: `api/frontend/api/_handlers/${domain.id}`,
      },
    ],
  }));

  const routeMapItems: SidebarItemConfig[] = routeMaps.map((route) => ({
    type: 'doc',
    id: `api/frontend/api/_handlers/${route.id}`,
    label: route.label,
  }));

  return [
    {
      type: 'category',
      label: 'By domain',
      collapsed: true,
      items: domainItems,
    },
    {
      type: 'category',
      label: 'Route maps',
      collapsed: true,
      items: routeMapItems,
    },
  ];
}

export function buildApiReferenceSidebarItems(): SidebarItemConfig[] {
  return [
    {
      type: 'doc',
      id: 'api/index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'HTTP handlers',
      collapsed: true,
      link: {type: 'doc', id: 'api/handlers/index'},
      items: buildHttpHandlerSidebarItems(),
    },
    {
      type: 'category',
      label: 'Server library',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'api/frontend/server'}],
    },
    {
      type: 'category',
      label: 'Frontend src',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'api/frontend/src'}],
    },
    {
      type: 'category',
      label: 'Contract API',
      collapsed: true,
      link: {type: 'doc', id: 'api/contracts/README'},
      items: [{type: 'autogenerated', dirName: 'api/contracts'}],
    },
  ];
}
