import type {SidebarItemConfig} from '@docusaurus/plugin-content-docs';

function autogen(dirName: string): SidebarItemConfig {
  return {type: 'autogenerated', dirName};
}

function doc(id: string, label?: string): SidebarItemConfig {
  return label ? {type: 'doc', id, label} : {type: 'doc', id};
}

function category(
  label: string,
  items: SidebarItemConfig[],
  linkId?: string,
): SidebarItemConfig {
  return {
    type: 'category',
    label,
    collapsed: true,
    ...(linkId ? {link: {type: 'doc', id: linkId}} : {}),
    items,
  };
}

/** Ops sidebar — one autogen lane per subfolder under docs/operations/. */
export function buildOperationsSidebarItems(): SidebarItemConfig[] {
  return [
    doc('operations/index', 'Overview'),

    category(
      'Deploy & release',
      [autogen('operations/deployment')],
      'operations/deployment/index',
    ),

    category(
      'Automation & keepers',
      [autogen('operations/automation'), autogen('operations/kpr')],
      'operations/automation/index',
    ),

    category('Wallet & signing', [autogen('operations/wallet')]),

    category('Vault & greenfield', [autogen('operations/vault')]),

    category('Solana & share mesh', [autogen('operations/solana')]),

    category('AKITA (grandfathered)', [autogen('operations/akita')]),

    category('AlfaClub, Hermit & agents', [autogen('operations/alfaclub')]),

    category('Analytics & Explore', [autogen('operations/analytics')]),

    category('Platform & database', [autogen('operations/platform')]),

    category(
      'Telegram & XMTP',
      [autogen('operations/messaging'), autogen('operations/agent-runtime')],
      'operations/deployment/eliza-runtime',
    ),

    category('Services', [autogen('operations/services')]),

    category('Incidents', [autogen('operations/incidents')]),

    category(
      'Archive & retired',
      [autogen('operations/archive')],
      'operations/archive/index',
    ),
  ];
}
