// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Script, console} from "forge-std/Script.sol";

import {DrandRandomnessSource} from "../contracts/utilities/lottery/randomness/DrandRandomnessSource.sol";
import {EIP2537Probe} from "../contracts/utilities/lottery/randomness/EIP2537Probe.sol";

/**
 * @title DeployDrandRandomnessSource
 * @notice Deploy `DrandRandomnessSource` pinned to drand quicknet, after a
 *         live-network check that the EIP-2537 BLS12-381 precompiles are
 *         actually available on the target chain.
 *
 * @dev    Why this script exists in addition to a generic deployer:
 *         - drand quicknet uses scheme `bls-unchained-g1-rfc9380`, so the
 *           group public key is on G2 (96 byte compressed -> 256 byte EIP-2537).
 *           We hard-code the canonical encoding so a wrong-encoding pubkey
 *           cannot ship.
 *         - drand could rotate the network and ship a new pubkey. The constant
 *           below is fetched on 2026-04-25 from
 *           `https://api.drand.sh/52db9ba.../info` and must match the live
 *           value at deploy time. The deployer asserts this off-chain
 *           (CI fetch) and on-chain (length check in constructor).
 *         - EIP-2537 is a Pectra feature on L1 (May 7, 2025). On the OP Stack /
 *           Base side it shipped with the Isthmus hard fork shortly after L1
 *           Pectra. The pairing-check precompile lives at 0x0f, **NOT** at
 *           0x10 (which is MAP_FP_TO_G1). Older chains will silently
 *           "succeed" on staticcall but return zero bytes — `EIP2537Probe`
 *           probes G1ADD at 0x0b and detects this.
 *
 * @dev    Required env vars:
 *         - PRIVATE_KEY: deployer / owner of the source
 *
 * @dev    Optional env vars:
 *         - DRAND_OWNER: contract owner (defaults to deployer)
 *         - DRAND_RELAYER: initial relayer to authorize (defaults to deployer)
 *         - SKIP_EIP2537_CHECK: set to "1" to bypass the precompile probe
 *           (only for local anvil chains that mock 0x0b/0x10)
 *         - ALLOW_UNAUTHORIZED_RELAYER: set to "1" to deploy with no
 *           bootstrap relayer when DRAND_OWNER is a third-party address
 *           (e.g. a multisig). Default behavior is to revert in that case,
 *           because shipping a `DrandRandomnessSource` with zero authorized
 *           relayers means every `submitRound` reverts with `NotRelayer`
 *           until the new owner runs `setRelayer(addr, true)`. Use this
 *           flag only when you have that follow-up transaction queued.
 *
 * @dev    Usage:
 *         forge script script/DeployDrandRandomnessSource.s.sol:DeployDrandRandomnessSource \
 *             --rpc-url $BASE_RPC_URL \
 *             --broadcast \
 *             -vvvv
 */
contract DeployDrandRandomnessSource is Script {
    // ---- drand quicknet pinned constants (fetched 2026-04-25) ----
    //
    // Source of truth: https://api.drand.sh/52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971/info
    //   {"public_key": "83cf0f28...e45a", "period": 3,
    //    "genesis_time": 1692803367, "schemeID": "bls-unchained-g1-rfc9380",
    //    "metadata": {"beaconID": "quicknet"}}
    //
    // Compressed G2 (96 bytes) decompressed and EIP-2537-encoded (256 bytes):
    //   Fp2 x = (x_c0 || x_c1), Fp2 y = (y_c0 || y_c1).
    //   Each Fp = 64-byte BE, padded from the 48-byte BLS12-381 base field.
    bytes32 internal constant QUICKNET_CHAIN_HASH =
        0x52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971;
    uint64 internal constant QUICKNET_GENESIS_TIME = 1692803367;
    uint32 internal constant QUICKNET_PERIOD = 3;

    function _quicknetGroupPubKey() internal pure returns (bytes memory) {
        // Generated by amoe/tools/zk/encode_drand_pk.py from the live `/info` JSON.
        return hex"00000000000000000000000000000000"
            hex"0d1fec758c921cc22b0e17e63aaf4bcb5ed66304de9cf809bd274ca73bab4af5a6e9c76a4bc09e76eae8991ef5ece45a"
            hex"00000000000000000000000000000000"
            hex"03cf0f2896adee7eb8b5f01fcad3912212c437e0073e911fb90022d3e760183c8c4b450b6a0a6c3ac6a5776a2d106451"
            hex"00000000000000000000000000000000"
            hex"0e5db2b6bfbb01c867749cadffca88b36c24f3012ba09fc4d3022c5c37dce0f977d3adb5d183c7477c442b1f04515273"
            hex"00000000000000000000000000000000"
            hex"01a714f2edb74119a2f2b0d5a7c75ba902d163700a61bc224ededd8e63aef7be1aaf8e93d7a9718b047ccddb3eb5d68b";
    }

    function run() external returns (DrandRandomnessSource source) {
        uint256 privateKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(privateKey);

        address owner = vm.envOr("DRAND_OWNER", deployer);
        address relayer = vm.envOr("DRAND_RELAYER", deployer);
        bool skipProbe = vm.envOr("SKIP_EIP2537_CHECK", uint256(0)) == 1;

        console.log("Chain ID:           ", block.chainid);
        console.log("Deployer:           ", deployer);
        console.log("Owner:              ", owner);
        console.log("Initial relayer:    ", relayer);
        console.log("EIP-2537 probe:     ", skipProbe ? "SKIPPED" : "ENABLED");

        // Sanity-check: BLS12-381 precompiles live before we deploy the
        // pairing-dependent contract. Reverts loudly here, not in production
        // when a relayer first submits a round.
        if (!skipProbe) {
            require(
                EIP2537Probe.isAvailable(),
                "EIP-2537 precompiles missing on this chain (chain pre-Pectra?)"
            );
            console.log("EIP-2537 precompile probe: PASSED");
        }

        bytes memory pk = _quicknetGroupPubKey();
        require(pk.length == 256, "pk encoding length");
        console.log("drand chain hash:");
        console.logBytes32(QUICKNET_CHAIN_HASH);
        console.log("drand genesis_time: ", QUICKNET_GENESIS_TIME);
        console.log("drand period:       ", QUICKNET_PERIOD);
        console.log("drand pk length:    ", pk.length);

        vm.startBroadcast(privateKey);

        source = new DrandRandomnessSource(
            owner,
            QUICKNET_CHAIN_HASH,
            QUICKNET_GENESIS_TIME,
            QUICKNET_PERIOD,
            pk
        );

        // -------------------------------------------------------------
        // Authorize the initial relayer. Multi-relayer support comes later
        // via setRelayer; this is the bootstrap.
        //
        // Only the contract owner can call `setRelayer`, so we can only do
        // the bootstrap inside this broadcast when the deployer is also the
        // owner. If `DRAND_OWNER` was overridden to a different address
        // (multisig, governance) we cannot reach `setRelayer` from here.
        //
        // Previously this branch silently fell through, leaving the source
        // with zero authorized relayers. Every `submitRound` would then
        // revert with `NotRelayer` until the new owner ran `setRelayer`
        // separately, with no on-chain trail of what was supposed to
        // happen. We now either:
        //   (a) explicitly revert (default), forcing the caller to
        //       acknowledge the deferred bootstrap, OR
        //   (b) when ALLOW_UNAUTHORIZED_RELAYER=1 is set, log the exact
        //       follow-up call the new owner needs to make and proceed.
        // -------------------------------------------------------------
        if (owner == deployer) {
            source.setRelayer(relayer, true);
            console.log("Authorized initial relayer:", relayer);
        } else {
            bool allowUnauthorized =
                vm.envOr("ALLOW_UNAUTHORIZED_RELAYER", uint256(0)) == 1;
            console.log("WARNING: deployer is NOT DRAND_OWNER.");
            console.log(
                "WARNING: cannot authorize DRAND_RELAYER in this broadcast."
            );
            console.log(
                "WARNING: DRAND_OWNER must call, on the deployed source:"
            );
            console.log("  setRelayer(<relayer>, true)");
            console.log("  selector:        0xecd8dc3a");
            console.log("  relayer argument:", relayer);
            require(
                allowUnauthorized,
                "deployer != DRAND_OWNER; cannot bootstrap relayer. Set ALLOW_UNAUTHORIZED_RELAYER=1 to deploy anyway and follow up with the owner."
            );
        }

        vm.stopBroadcast();

        console.log("Deployed DrandRandomnessSource:", address(source));
    }
}
