#!/usr/bin/env bash
set -euo pipefail

# Generates `frontend/src/deploy/bytecode.generated.ts` from Foundry artifacts.
#
# This file is used by the frontend (CREATE2 address prediction) and by Foundry
# scripts (e.g. seeding the UniversalBytecodeStore).
#
# Usage:
#   ./script/generate_frontend_deploy_bytecode.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/frontend/src/deploy/bytecode.generated.ts"

cd "$ROOT_DIR"

echo "Generating deploy bytecode → frontend/src/deploy/bytecode.generated.ts"

# Ensure artifacts are up to date.
#
# We only need contract creation bytecode for deployments. Tests/scripts can be out-of-sync
# (e.g. constructor arg changes) and shouldn't block regenerating frontend deploy bytecode.
forge build --skip test --skip script >/dev/null

bytecode() {
  # Prints creation bytecode without the leading "0x" (we add it in TS as `'0x' + '...'`
  # to avoid naive scanners misclassifying onchain bytecode as secrets).
  local bc
  bc="$(forge inspect "$1" bytecode | tail -n 1)"
  bc="${bc#0x}"
  printf "%s" "$bc"
}

cat >"$OUT_FILE" <<'EOF'
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
// Generated by: script/generate_frontend_deploy_bytecode.sh
//
// This file contains contract *creation bytecode* required for Phase-2 AA (CREATE2) deployments.

export const DEPLOY_BYTECODE = {
EOF

printf "  CreatorOVault: '0x' + '%s',\n" "$(bytecode CreatorOVault)" >>"$OUT_FILE"
printf "  CreatorOVaultWrapper: '0x' + '%s',\n" "$(bytecode CreatorOVaultWrapper)" >>"$OUT_FILE"
printf "  CreatorShareOFT: '0x' + '%s',\n" "$(bytecode CreatorShareOFT)" >>"$OUT_FILE"
printf "  OFTBootstrapRegistry: '0x' + '%s',\n" "$(bytecode OFTBootstrapRegistry)" >>"$OUT_FILE"
printf "  CreatorGaugeController: '0x' + '%s',\n" "$(bytecode CreatorGaugeController)" >>"$OUT_FILE"
printf "  CCALaunchStrategy: '0x' + '%s',\n" "$(bytecode CCALaunchStrategy)" >>"$OUT_FILE"
printf "  CreatorOracle: '0x' + '%s',\n" "$(bytecode CreatorOracle)" >>"$OUT_FILE"
printf "  PayoutRouter: '0x' + '%s',\n" "$(bytecode PayoutRouter)" >>"$OUT_FILE"
printf "  VaultShareBurnStream: '0x' + '%s',\n" "$(bytecode VaultShareBurnStream)" >>"$OUT_FILE"
printf "  CreatorCharmStrategy: '0x' + '%s',\n" "$(bytecode CreatorCharmStrategy)" >>"$OUT_FILE"
printf "  AjnaVaultAuth: '0x' + '%s',\n" "$(bytecode AjnaVaultAuth)" >>"$OUT_FILE"
printf "  AjnaERC4626Vault: '0x' + '%s',\n" "$(bytecode AjnaERC4626Vault)" >>"$OUT_FILE"
printf "  ERC4626StrategyAdapter: '0x' + '%s',\n" "$(bytecode ERC4626StrategyAdapter)" >>"$OUT_FILE"
printf "  SolanaStrategy: '0x' + '%s',\n" "$(bytecode SolanaStrategy)" >>"$OUT_FILE"

cat >>"$OUT_FILE" <<'EOF'
} as const;
EOF

echo "Done."
