#!/usr/bin/env bash
set -euo pipefail

# Generates `frontend/src/deploy/bytecode.generated.ts` from Foundry artifacts.
#
# This file is used by the frontend (CREATE2 address prediction) and by Foundry
# scripts (e.g. seeding the UniversalBytecodeStore).
#
# Usage:
#   ./script/generate_frontend_deploy_bytecode.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/frontend/src/deploy/bytecode.generated.ts"

# shellcheck source=script/lib/resolve_foundry_artifact.sh
source "$ROOT_DIR/script/lib/resolve_foundry_artifact.sh"

cd "$ROOT_DIR"

echo "Generating deploy bytecode → frontend/src/deploy/bytecode.generated.ts"

# Ensure artifacts are up to date.
#
# We only need contract creation bytecode for deployments. Tests/scripts can be out-of-sync
# (e.g. constructor arg changes) and shouldn't block regenerating frontend deploy bytecode.
forge build --skip test --skip script >/dev/null

artifact_path() {
  local contract="$1"
  local sol_dir
  case "$contract" in
    DeploymentBatcher|DeploymentBatcherPhase1Module|DeploymentBatcherPhase2Module|DeploymentBatcherPhase3Helper|DeploymentBatcherShareMeshHelper|DeploymentBatcherUtilsHelper)
      sol_dir="$ROOT_DIR/out/DeploymentBatcher.sol"
      ;;
    CreatorOracleQuoteLib)
      # Multi-solc emits CreatorOracleQuoteLib.<solc>.json; the shared resolver
      # prefers the bare artifact then newest via sort -V (lex sort ranks 0.8.9
      # above 0.8.34 and wrong CREATE2 links).
      sol_dir="$ROOT_DIR/out/CreatorOracleQuoteLib.sol"
      ;;
    *)
      sol_dir="$ROOT_DIR/out/${contract}.sol"
      ;;
  esac
  # Print resolved path even when missing (caller errors with the expected path).
  resolve_foundry_artifact "$sol_dir" "$contract" || true
}

bytecode() {
  # Prints creation bytecode without the leading "0x" (we add it in TS as `'0x' + '...'`
  # to avoid naive scanners misclassifying onchain bytecode as secrets).
  local contract="$1"
  local artifact
  artifact="$(artifact_path "$contract")"
  if [[ ! -f "$artifact" ]]; then
    echo "Missing artifact: $artifact (run forge build --skip test --skip script first)" >&2
    return 1
  fi
  # Fully link external libraries (Foundry CREATE2 salt 0 @ EIP-2470).
  # Do NOT truncate at `__$...$__` placeholders — that yields broken initcode.
  python3 "$ROOT_DIR/script/lib/extract_linked_bytecode.py" "$artifact" "$ROOT_DIR"
}

# IMPORTANT: do not embed `$(bytecode …)` directly inside `printf` args.
# With `set -e`, a failing command substitution in that position does not abort
# the script — it silently writes empty creation bytecode into DEPLOY_BYTECODE.
append_deploy_bytecode() {
  local name="$1"
  local hex
  hex="$(bytecode "$name")" || {
    echo "Failed to extract creation bytecode for ${name}" >&2
    exit 1
  }
  if [[ -z "$hex" || ! "$hex" =~ ^[0-9a-fA-F]+$ ]]; then
    echo "Invalid/empty creation bytecode for ${name} (refusing to write DEPLOY_BYTECODE)" >&2
    exit 1
  fi
  printf "  %s: '0x' + '%s',\n" "$name" "$hex" >>"$OUT_FILE"
}

cat >"$OUT_FILE" <<'EOF'
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
// Generated by: script/generate_frontend_deploy_bytecode.sh
//
// This file contains contract *creation bytecode* required for Phase-2 AA (CREATE2) deployments.

export const DEPLOY_BYTECODE = {
EOF

append_deploy_bytecode CreatorOVault
append_deploy_bytecode AgentOVault
append_deploy_bytecode CreatorOVaultWrapper
append_deploy_bytecode AgentOVaultWrapper
append_deploy_bytecode CreatorShareOFT
append_deploy_bytecode AgentShareOFT
append_deploy_bytecode OFTBootstrapRegistry
append_deploy_bytecode CreatorGaugeController
append_deploy_bytecode AgentGaugeController
append_deploy_bytecode CCALaunchArm
append_deploy_bytecode CreatorOracleQuoteLib
append_deploy_bytecode CreatorOracle
append_deploy_bytecode AgentOracle
append_deploy_bytecode CreatorPayoutRouter
append_deploy_bytecode AgentRevenueRouter
append_deploy_bytecode VaultShareBurnStream
append_deploy_bytecode CreatorCoinPolicyController
append_deploy_bytecode AgentRevenuePolicyController
append_deploy_bytecode CharmStrategy4626
append_deploy_bytecode AjnaVaultAuth
append_deploy_bytecode AjnaERC4626Vault
append_deploy_bytecode ERC4626StrategyAdapter
append_deploy_bytecode ApprovedV4HooksRegistry
append_deploy_bytecode OVaultLPManager
append_deploy_bytecode OVaultImpairmentClaims
append_deploy_bytecode OVaultRecoveryEscrow

cat >>"$OUT_FILE" <<'EOF'
} as const;
EOF

cp "$OUT_FILE" "$ROOT_DIR/frontend/shared/deploy/bytecode.generated.ts"

echo "Done."
