#!/usr/bin/env bash
set -euo pipefail

# Generates `frontend/src/deploy/bytecode.generated.ts` from Foundry artifacts.
#
# This file is used by the frontend (CREATE2 address prediction) and by Foundry
# scripts (e.g. seeding the UniversalBytecodeStore).
#
# Usage:
#   ./script/generate_frontend_deploy_bytecode.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/frontend/src/deploy/bytecode.generated.ts"

cd "$ROOT_DIR"

echo "Generating deploy bytecode → frontend/src/deploy/bytecode.generated.ts"

# Ensure artifacts are up to date.
#
# We only need contract creation bytecode for deployments. Tests/scripts can be out-of-sync
# (e.g. constructor arg changes) and shouldn't block regenerating frontend deploy bytecode.
forge build --skip test --skip script >/dev/null

artifact_path() {
  local contract="$1"
  case "$contract" in
    DeploymentBatcher|DeploymentBatcherPhase1Module|DeploymentBatcherPhase2Module|DeploymentBatcherPhase3Helper|DeploymentBatcherShareMeshHelper|DeploymentBatcherUtilsHelper)
      printf "%s/out/DeploymentBatcher.sol/%s.json" "$ROOT_DIR" "$contract"
      ;;
    ApprovedV4HooksRegistry|OVaultLPManager)
      printf "%s/out/%s.sol/%s.json" "$ROOT_DIR" "$contract" "$contract"
      ;;
    *)
      printf "%s/out/%s.sol/%s.json" "$ROOT_DIR" "$contract" "$contract"
      ;;
  esac
}

bytecode() {
  # Prints creation bytecode without the leading "0x" (we add it in TS as `'0x' + '...'`
  # to avoid naive scanners misclassifying onchain bytecode as secrets).
  local contract="$1"
  local artifact
  artifact="$(artifact_path "$contract")"
  if [[ ! -f "$artifact" ]]; then
    echo "Missing artifact: $artifact (run forge build --skip test --skip script first)" >&2
    exit 1
  fi
  # Fully link external libraries (Foundry CREATE2 salt 0 @ EIP-2470).
  # Do NOT truncate at `__$...$__` placeholders — that yields broken initcode.
  python3 "$ROOT_DIR/script/lib/extract_linked_bytecode.py" "$artifact" "$ROOT_DIR"
}

cat >"$OUT_FILE" <<'EOF'
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
// Generated by: script/generate_frontend_deploy_bytecode.sh
//
// This file contains contract *creation bytecode* required for Phase-2 AA (CREATE2) deployments.

export const DEPLOY_BYTECODE = {
EOF

printf "  CreatorOVault: '0x' + '%s',\n" "$(bytecode CreatorOVault)" >>"$OUT_FILE"
printf "  AgentOVault: '0x' + '%s',\n" "$(bytecode AgentOVault)" >>"$OUT_FILE"
printf "  CreatorOVaultWrapper: '0x' + '%s',\n" "$(bytecode CreatorOVaultWrapper)" >>"$OUT_FILE"
printf "  AgentOVaultWrapper: '0x' + '%s',\n" "$(bytecode AgentOVaultWrapper)" >>"$OUT_FILE"
printf "  CreatorShareOFT: '0x' + '%s',\n" "$(bytecode CreatorShareOFT)" >>"$OUT_FILE"
printf "  AgentShareOFT: '0x' + '%s',\n" "$(bytecode AgentShareOFT)" >>"$OUT_FILE"
printf "  OFTBootstrapRegistry: '0x' + '%s',\n" "$(bytecode OFTBootstrapRegistry)" >>"$OUT_FILE"
printf "  CreatorGaugeController: '0x' + '%s',\n" "$(bytecode CreatorGaugeController)" >>"$OUT_FILE"
printf "  AgentGaugeController: '0x' + '%s',\n" "$(bytecode AgentGaugeController)" >>"$OUT_FILE"
printf "  CCALaunchArm: '0x' + '%s',\n" "$(bytecode CCALaunchArm)" >>"$OUT_FILE"
printf "  CreatorOracle: '0x' + '%s',\n" "$(bytecode CreatorOracle)" >>"$OUT_FILE"
printf "  AgentOracle: '0x' + '%s',\n" "$(bytecode AgentOracle)" >>"$OUT_FILE"
printf "  CreatorPayoutRouter: '0x' + '%s',\n" "$(bytecode CreatorPayoutRouter)" >>"$OUT_FILE"
printf "  AgentRevenueRouter: '0x' + '%s',\n" "$(bytecode AgentRevenueRouter)" >>"$OUT_FILE"
printf "  VaultShareBurnStream: '0x' + '%s',\n" "$(bytecode VaultShareBurnStream)" >>"$OUT_FILE"
printf "  CreatorCoinPolicyController: '0x' + '%s',\n" "$(bytecode CreatorCoinPolicyController)" >>"$OUT_FILE"
printf "  AgentRevenuePolicyController: '0x' + '%s',\n" "$(bytecode AgentRevenuePolicyController)" >>"$OUT_FILE"
printf "  CharmStrategy4626: '0x' + '%s',\n" "$(bytecode CharmStrategy4626)" >>"$OUT_FILE"
printf "  AjnaVaultAuth: '0x' + '%s',\n" "$(bytecode AjnaVaultAuth)" >>"$OUT_FILE"
printf "  AjnaERC4626Vault: '0x' + '%s',\n" "$(bytecode AjnaERC4626Vault)" >>"$OUT_FILE"
printf "  ERC4626StrategyAdapter: '0x' + '%s',\n" "$(bytecode ERC4626StrategyAdapter)" >>"$OUT_FILE"
printf "  ApprovedV4HooksRegistry: '0x' + '%s',\n" "$(bytecode ApprovedV4HooksRegistry)" >>"$OUT_FILE"
printf "  OVaultLPManager: '0x' + '%s',\n" "$(bytecode OVaultLPManager)" >>"$OUT_FILE"
printf "  OVaultImpairmentClaims: '0x' + '%s',\n" "$(bytecode OVaultImpairmentClaims)" >>"$OUT_FILE"
printf "  OVaultRecoveryEscrow: '0x' + '%s',\n" "$(bytecode OVaultRecoveryEscrow)" >>"$OUT_FILE"

cat >>"$OUT_FILE" <<'EOF'
} as const;
EOF

cp "$OUT_FILE" "$ROOT_DIR/frontend/shared/deploy/bytecode.generated.ts"

echo "Done."
