import { useCallback, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import {
  Activity,
  BarChart3,
  CircleHelp,
  Droplets,
  ExternalLink,
  Share2,
  TrendingUp,
  X,
} from 'lucide-react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { getAddress, isAddress } from 'viem'
import { useQuery } from '@tanstack/react-query'

import { MetricChartPlot } from '@/components/explore/MetricChartPlot'
import { PageMeta } from '@/components/seo/PageMeta'
import { ExploreCopyButton, ExploreStatRow } from '@/components/explore/ExploreUiPrimitives'
import { EthosBlurOrbs, EthosPageAmbience } from '@/components/explore/EthosPageAmbience'
import { ExploreEthosRefreshButton } from '@/components/explore/ExploreEthosRefreshButton'
import { useCreatorEthosPageTheme } from '@/components/explore/ethosPageTheme'
import { cn } from '@/lib/shared/utils'
import { TokenAvatar } from '@/components/swap/TokenAvatar'
import { LoadingBlock, LoadingText } from '@/components/ui/LoadingState'
import { useIdentity } from '@/hooks/useIdentity'
import { fetchZoraCoin } from '@/lib/zora/client'
import { useZoraProfile } from '@/lib/zora/hooks'
import { usePoolHistory, type PoolHistoryData } from '@/lib/uniswap/hooks'
import { getPoolSwaps, getPoolsByToken } from '@/lib/uniswap/client'
import type { UniswapPool, UniswapSwap } from '@/lib/uniswap/types'
import {
  formatCount,
  formatDateLabel,
  formatShortAddress,
  formatTimestamp,
  formatTokenAmount,
  formatUsd,
  isSupportedExploreChain,
  parseNumber,
  toDisplayAssetUrl,
} from '@/features/explore/exploreShared'

type PeriodKey = '1H' | '1D' | '1W' | '1M' | '1Y'
type MetricKey = 'liquidity' | 'volume' | 'fees' | 'price'

const PERIOD_TO_TIMEFRAME: Record<PeriodKey, '1h' | '1d' | '1w' | '1m' | '1y'> = {
  '1H': '1h',
  '1D': '1d',
  '1W': '1w',
  '1M': '1m',
  '1Y': '1y',
}

const PERIODS: PeriodKey[] = ['1H', '1D', '1W', '1M', '1Y']

const METRICS: Array<{ key: MetricKey; label: string; icon: React.ReactNode }> = [
  { key: 'liquidity', label: 'Liquidity', icon: <Droplets className="w-3.5 h-3.5" /> },
  { key: 'volume', label: 'Volume', icon: <BarChart3 className="w-3.5 h-3.5" /> },
  { key: 'fees', label: 'Fees', icon: <Activity className="w-3.5 h-3.5" /> },
  { key: 'price', label: 'Price', icon: <TrendingUp className="w-3.5 h-3.5" /> },
]

const ZORA_TOKEN_LOGO_URL = '/brands/zora-token.svg'
const BASESCAN_ICON_URL =
  'https://green-decisive-crane-434.mypinata.cloud/ipfs/bafkreidse2dmc2h5myecpddbm53xwbn62yq4l4af7fnpi362prhk6f2hoi'
const UNISWAP_ICON_URL = '/protocols/uniswap.svg'

const SNAPSHOT_METRIC_HELP: Record<string, string> = {
  tvl: 'Total value currently held in the primary liquidity pool.',
  volume: 'Total traded notional during the selected time window.',
  fees: 'Estimated fees generated by trades during the selected time window.',
  tokenPrice: 'Latest observed token price from the selected pool.',
  priceChange: 'Percent change in token price across the selected time window.',
  liquidityVariance: 'Coefficient of variation for liquidity. Higher means liquidity fluctuates more over time.',
  priceVariance: 'Coefficient of variation for price. Higher means price fluctuates more over time.',
}

function renderSnapshotLabel(label: string, tooltip?: string): React.ReactNode {
  const tooltipText = tooltip ?? ''
  return (
    <span className="inline-flex items-center gap-1.5">
      <span>{label}</span>
      <span
        className="inline-flex items-center text-zinc-500 hover:text-zinc-300 transition-colors"
        title={tooltipText}
        aria-label={`${label} info: ${tooltipText}`}
      >
        <CircleHelp className="h-3.5 w-3.5" />
      </span>
    </span>
  )
}

function formatTokenPrice(value: number): string {
  if (!Number.isFinite(value) || value <= 0) return '$0.00'
  if (value < 0.0001) return `$${value.toExponential(2)}`
  if (value < 0.01) return `$${value.toFixed(6)}`
  if (value < 1) return `$${value.toFixed(4)}`
  if (value < 1000) return `$${value.toFixed(2)}`
  return `$${value.toLocaleString(undefined, { maximumFractionDigits: 2 })}`
}

function formatPercent(value: number): string {
  if (!Number.isFinite(value)) return '0.00%'
  const sign = value >= 0 ? '+' : '-'
  return `${sign}${Math.abs(value).toFixed(2)}%`
}

function formatSupply(value: number): string {
  if (!Number.isFinite(value) || value <= 0) return '-'
  if (value >= 1_000_000_000) return `${(value / 1_000_000_000).toFixed(2)}B`
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(2)}M`
  if (value >= 1_000) return `${(value / 1_000).toFixed(2)}K`
  return value.toLocaleString(undefined, { maximumFractionDigits: 0 })
}

function calcCoefficientOfVariation(values: number[]): number | null {
  const cleaned = values.filter((v) => Number.isFinite(v) && v > 0)
  if (cleaned.length < 2) return null
  const mean = cleaned.reduce((a, b) => a + b, 0) / cleaned.length
  if (mean <= 0) return null
  const variance = cleaned.reduce((acc, v) => acc + (v - mean) ** 2, 0) / cleaned.length
  const std = Math.sqrt(variance)
  return (std / mean) * 100
}

// Metric -> gradient stops. Uses Base Blue family for liquidity/volume and
// the semantic green for fees to match product-standard dark theming.
const METRIC_COLORS: Record<MetricKey, { primary: string; secondary: string }> = {
  liquidity: { primary: '#38BDF8', secondary: '#0EA5E9' },
  volume: { primary: '#A78BFA', secondary: '#7C3AED' },
  fees: { primary: '#34D399', secondary: '#10B981' },
  price: { primary: '#F4F4F5', secondary: '#A1A1AA' },
}

// Extracts the raw (absolute) value for a given metric from a history point.
function extractMetricValue(point: PoolHistoryPoint, metric: MetricKey): number {
  switch (metric) {
    case 'liquidity':
      return point.tvlUSD
    case 'volume':
      return point.volumeUSD
    case 'fees':
      return point.feesUSD
    case 'price':
      return point.close ?? 0
  }
}

// Formats an absolute metric value for display. Price is sub-dollar so it
// needs the small-number formatter; everything else is USD notional.
function formatMetricValue(metric: MetricKey, value: number): string {
  return metric === 'price' ? formatTokenPrice(value) : formatUsd(value)
}

/**
 * Pick "nice" round tick values spanning the data range for a given target
 * tick count. Uses the standard 1/2/5 × 10^n step family so tick values
 * land on human-readable numbers (e.g. 0, 200K, 400K, 600K for TVL; or
 * 0.094, 0.096, 0.098 for a tight price band).
 *
 * `includeZero` controls whether the domain is anchored at 0. Most series
 * (volume, fees, liquidity) read more naturally when the floor is zero;
 * price bands are better bounded by the data range so the line isn't
 * pinned to the top of the card.
 */
function niceYTicks(
  values: number[],
  count: number = 4,
  { includeZero = true }: { includeZero?: boolean } = {},
): number[] {
  const finite = values.filter((v) => Number.isFinite(v))
  if (finite.length === 0) return []
  const rawMin = Math.min(...finite)
  const rawMax = Math.max(...finite)
  const min = includeZero ? Math.min(0, rawMin) : rawMin
  const max = Math.max(rawMax, min)
  if (max <= min) return [min]

  const span = max - min
  const roughStep = span / Math.max(1, count)
  const magnitude = Math.pow(10, Math.floor(Math.log10(Math.abs(roughStep))))
  const normalized = roughStep / magnitude
  const niceStep =
    magnitude * (normalized < 1.5 ? 1 : normalized < 3 ? 2 : normalized < 7 ? 5 : 10)
  const niceMin = Math.floor(min / niceStep) * niceStep
  const niceMax = Math.ceil(max / niceStep) * niceStep

  const ticks: number[] = []
  for (let v = niceMin; v <= niceMax + niceStep * 0.0001; v += niceStep) {
    ticks.push(Number(v.toFixed(10)))
  }
  return ticks
}

/**
 * Pick up to `count` evenly-spaced label indices from a series so the
 * external X-axis doesn't crowd the card. Always includes the first and
 * last index so the user sees the full time window at a glance.
 */
function pickXTickIndices(totalPoints: number, count: number = 4): number[] {
  if (totalPoints === 0) return []
  if (totalPoints === 1) return [0]
  const n = Math.max(2, Math.min(count, totalPoints))
  const indices: number[] = []
  for (let i = 0; i < n; i++) {
    indices.push(Math.round((i * (totalPoints - 1)) / (n - 1)))
  }
  // Dedup in case two rounded values collided (short series).
  return Array.from(new Set(indices))
}

type PoolHistoryPoint = {
  timestamp: number
  tvlUSD: number
  volumeUSD: number
  feesUSD: number
  close?: number
}

/**
 * Combined multi-series chart. Overlays liquidity / volume / fees / price
 * on a single LineChart, normalized to percent-change-from-start so the
 * wildly-different magnitudes share one Y axis. Each metric is independently
 * toggleable via the chip row above the chart, and a live readout surfaces
 * the absolute value + delta for every active metric at the hovered bucket.
 */
/**
 * Per-metric chart with viz tuned to the metric's semantics:
 *   - Price     \u2192 smooth LineChart (continuous spot movement)
 *   - Volume    \u2192 BarChart (per-bucket USD notional)
 *   - Fees      \u2192 BarChart of *cumulative* fees (monotonically growing)
 *   - Liquidity \u2192 stacked BarChart split by the pool's two tokens
 *
 * Every metric shares the same scrubber readout so the bucket under the
 * cursor (or the latest bucket when idle) is always legible.
 */
function MetricChart({
  points,
  metric,
  pool,
  period,
}: {
  points: PoolHistoryPoint[]
  metric: MetricKey
  pool: PoolHistoryData['pool']
  period: string
}) {
  const labels = useMemo(() => points.map((p) => formatTimestamp(p.timestamp)), [points])

  // Per-bucket raw values for the active metric. Fees gets transformed into
  // a cumulative running sum so each bar represents total fees accrued up
  // to and including that bucket.
  const values = useMemo(() => {
    const raw = points.map((p) => extractMetricValue(p, metric))
    if (metric === 'fees') {
      let running = 0
      return raw.map((v) => (running += Number.isFinite(v) ? v : 0))
    }
    return raw
  }, [points, metric])

  const [hoverIndex, setHoverIndex] = useState<number | null>(null)
  const handleScrub = useCallback<(index: number | undefined) => void>((index) => {
    setHoverIndex(typeof index === 'number' && Number.isFinite(index) ? index : null)
  }, [])

  if (points.length === 0) {
    return (
      <div className="flex h-[320px] items-center justify-center rounded-xl border border-white/8 bg-transparent text-sm text-zinc-600">
        No historical pool data
      </div>
    )
  }

  const palette = METRIC_COLORS[metric]
  const label = METRICS.find((m) => m.key === metric)?.label ?? metric
  const readoutIndex =
    hoverIndex != null && hoverIndex >= 0 && hoverIndex < points.length
      ? hoverIndex
      : points.length - 1
  const readoutValue = values[readoutIndex] ?? 0
  const readoutTimestamp = labels[readoutIndex] ?? ''

  // Liquidity decomposition: approximate historical per-token TVL by
  // applying the *current* pool's token0/token1 USD shares to each
  // bucket's `tvlUSD`. The approximation drifts whenever the pool's
  // composition has shifted, but still gives users a clear read on which
  // side of the pair the pool is weighted toward.
  const composition = metric === 'liquidity' && pool ? pool : null
  const token0Share = composition?.token0UsdShare ?? null
  const token1Share = composition?.token1UsdShare ?? null
  const hasStackedLiquidity =
    composition != null &&
    typeof token0Share === 'number' &&
    typeof token1Share === 'number' &&
    token0Share + token1Share > 0

  const plotMode =
    metric === 'price' ? 'line' : metric === 'liquidity' && hasStackedLiquidity ? 'stacked-bar' : 'bar'

  // Bespoke Y-axis ticks and the domain they span. For stacked liquidity
  // we compute ticks off the *total* tvlUSD (not each stack individually)
  // so the Y ticks match what the eye sees for the full bar. Price is the
  // only metric that doesn't anchor to zero — it usually trades in a
  // narrow band well above 0 and pinning the floor to 0 would flatten
  // all variation.
  const yTicks = niceYTicks(values, 4, { includeZero: metric !== 'price' })
  const yTickDomain =
    yTicks.length > 0
      ? { min: yTicks[0]!, max: yTicks[yTicks.length - 1]! }
      : { min: 0, max: 1 }

  // X-axis ticks: 4 evenly-spaced labels (first, 1/3, 2/3, last).
  const xTickIndices = pickXTickIndices(labels.length, 4)

  const showLiquidityBreakdown = metric === 'liquidity' && hasStackedLiquidity

  return (
    <div>
      {/* Top row — chart card on the left, bespoke vertical Y-axis on the
          right. The Y-axis column mirrors the card's flex-col layout with
          invisible placeholders for the readout (and optional liquidity
          breakdown) so the ticks naturally align with the plot area
          regardless of which metric is active. */}
      <div className="grid grid-cols-[1fr_auto] items-stretch gap-1">
        <div className="flex h-[420px] flex-col rounded-xl border border-white/8 bg-transparent p-4">
          <div className="flex items-baseline justify-between gap-3">
            <div className="flex items-baseline gap-2">
              <span
                className="inline-block h-1.5 w-1.5 shrink-0 rounded-full"
                style={{ background: palette.primary }}
                aria-hidden="true"
              />
              <span className="text-[11px] uppercase tracking-[0.14em] text-zinc-500">
                {label}
                {metric === 'fees' ? ' (cumulative)' : ''}
              </span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="tabular-nums text-sm font-semibold text-white">
                {formatMetricValue(metric, readoutValue)}
              </span>
              <span className="text-[10px] tabular-nums text-zinc-500">{readoutTimestamp}</span>
            </div>
          </div>

          {/* Per-token breakdown readout for the liquidity view. */}
          {showLiquidityBreakdown && composition ? (
            <div className="mt-2 grid grid-cols-2 gap-3 text-[11px] tabular-nums">
              <LiquidityShareReadout
                symbol={composition.token0Symbol}
                usd={readoutValue * (token0Share ?? 0)}
                share={token0Share ?? 0}
                color={palette.primary}
              />
              <LiquidityShareReadout
                symbol={composition.token1Symbol}
                usd={readoutValue * (token1Share ?? 0)}
                share={token1Share ?? 0}
                color={palette.secondary}
              />
            </div>
          ) : null}

          <div className="mt-3 min-h-0 w-full flex-1">
            <MetricChartPlot
              mode={plotMode}
              values={values}
              yDomain={yTickDomain}
              primaryColor={palette.primary}
              secondaryColor={palette.secondary}
              token0Share={token0Share}
              token1Share={token1Share}
              onScrub={handleScrub}
            />
          </div>
        </div>

        {/* Vertical Y-axis column. Mirrors the card's flex-col structure
            (with invisible placeholders for the readout + optional liquidity
            breakdown) so the tick labels line up with the plot area
            top-to-bottom. Ticks are rendered high\u2192low since Y increases
            upward on the chart. */}
        {yTicks.length > 1 ? (
          <div className="flex h-[420px] min-w-[46px] flex-col px-0.5 py-4 text-right">
            <div
              className="invisible flex items-baseline justify-between gap-3"
              aria-hidden="true"
            >
              <span className="text-[11px]">{label}</span>
              <span className="text-sm">.</span>
            </div>
            {showLiquidityBreakdown ? (
              <div
                className="invisible mt-2 grid grid-cols-2 gap-3 text-[11px]"
                aria-hidden="true"
              >
                <span>placeholder</span>
                <span>placeholder</span>
              </div>
            ) : null}
            <div className="mt-3 flex flex-1 flex-col justify-between text-[10px] tabular-nums text-zinc-500">
              {[...yTicks].reverse().map((t, i) => (
                <span key={`${t}-${i}`}>{formatMetricValue(metric, t)}</span>
              ))}
            </div>
          </div>
        ) : null}
      </div>

      {/* External X-axis — time labels at the bottom of the component,
          OUTSIDE the card boundary. */}
      {xTickIndices.length > 0 ? (
        <div className="mt-2 flex items-center justify-between px-1 text-[10px] tabular-nums text-zinc-500">
          {xTickIndices.map((i) => (
            <span key={i}>{labels[i]}</span>
          ))}
        </div>
      ) : null}

      {/* Subtle caveat copy for the liquidity approximation. */}
      {metric === 'liquidity' && hasStackedLiquidity ? (
        <div className="mt-2 text-[10px] text-zinc-600">
          Composition based on the pool's current token split, applied across {period}.
        </div>
      ) : null}
    </div>
  )
}

function LiquidityShareReadout({
  symbol,
  usd,
  share,
  color,
}: {
  symbol: string | null
  usd: number
  share: number
  color: string
}) {
  return (
    <div className="flex min-w-0 items-baseline gap-1.5">
      <span
        className="inline-block h-1.5 w-1.5 shrink-0 rounded-full"
        style={{ background: color }}
        aria-hidden="true"
      />
      <span className="truncate text-zinc-500">{symbol ?? '\u2014'}</span>
      <span className="ml-auto text-white">{formatUsd(usd)}</span>
      <span className="text-zinc-500">{(share * 100).toFixed(1)}%</span>
    </div>
  )
}

function PoolTokenHeader({
  address,
  symbol,
}: {
  address?: string | null
  symbol: string
}) {
  return (
    <span className="inline-flex items-center justify-end gap-1.5">
      <TokenAvatar
        token={
          address
            ? {
                address,
                symbol,
                chainId: 8453,
              }
            : undefined
        }
        symbol={symbol}
        size={16}
        withFallbackLabel
      />
      <span>{symbol}</span>
    </span>
  )
}

function WalletIdentityCell({ wallet, txHash }: { wallet: string; txHash: string }) {
  const identity = useIdentity(wallet)
  const short = formatShortAddress(wallet, '')
  const label =
    identity.loading || identity.source === 'address' ? short : (identity.displayName?.trim() || short)
  const showSecondary = !identity.loading && identity.source !== 'address'
  const textClass = txHash ? 'text-zinc-300 hover:text-white transition-colors' : 'text-zinc-400'

  const content = (
    <span className="inline-flex items-end gap-1.5">
      <span className={textClass}>{label}</span>
      {showSecondary ? <span className="text-[10px] text-zinc-500">{short}</span> : null}
    </span>
  )

  if (!txHash) return content

  return (
    <a href={`https://basescan.org/tx/${txHash}`} target="_blank" rel="noopener noreferrer">
      {content}
    </a>
  )
}

export function ExploreContentDetail() {
  const params = useParams()
  const chain = String(params.chain ?? '').trim()
  const contentCoinAddressRaw = String(params.contentCoinAddress ?? '').trim()

  const [selectedPeriod, setSelectedPeriod] = useState<PeriodKey>('1D')
  // Single-metric view — each metric renders in its own specialised viz
  // (line for price, bars for volume, cumulative bars for fees, stacked
  // token-composition bars for liquidity). Defaults to `price` because
  // that is the metric traders check first.
  const [selectedMetric, setSelectedMetric] = useState<MetricKey>('price')
  const [isImageLightboxOpen, setIsImageLightboxOpen] = useState(false)
  const [isSwapTrayOpen, setIsSwapTrayOpen] = useState(false)

  const contentCoinAddress = isAddress(contentCoinAddressRaw) ? getAddress(contentCoinAddressRaw) : null
  const timeframe = PERIOD_TO_TIMEFRAME[selectedPeriod]

  const { data: coin, isLoading: coinLoading } = useQuery({
    queryKey: ['coin', contentCoinAddress],
    queryFn: async () => {
      if (!contentCoinAddress) return null
      return fetchZoraCoin(contentCoinAddress as `0x${string}`, 8453)
    },
    enabled: Boolean(contentCoinAddress),
    staleTime: 30_000,
  })

  const { data: pools = [], isLoading: poolsLoading } = useQuery({
    queryKey: ['uniswap', 'poolsByToken', contentCoinAddress],
    queryFn: async () => {
      if (!contentCoinAddress) return []
      return getPoolsByToken(contentCoinAddress)
    },
    enabled: Boolean(contentCoinAddress),
    staleTime: 60_000,
  })

  const { data: history, isLoading: historyLoading } = usePoolHistory(contentCoinAddress ?? undefined, timeframe, {
    enabled: Boolean(contentCoinAddress),
  })

  const primaryPool = useMemo<UniswapPool | null>(() => {
    if (!pools || pools.length === 0) return null
    return [...pools].sort((a, b) => parseNumber(b.totalValueLockedUSD) - parseNumber(a.totalValueLockedUSD))[0] ?? null
  }, [pools])

  const { data: swaps = [], isLoading: swapsLoading } = useQuery({
    queryKey: ['uniswap', 'poolSwaps', primaryPool?.id],
    queryFn: async () => {
      if (!primaryPool?.id) return []
      return getPoolSwaps(primaryPool.id, 25)
    },
    enabled: Boolean(primaryPool?.id),
    staleTime: 30_000,
  })

  const activityRows = useMemo(() => {
    const contentAddressLower = contentCoinAddress?.toLowerCase() ?? ''
    return (swaps ?? []).map((swap: UniswapSwap) => {
      const amount0 = parseNumber(swap.amount0)
      const amount1 = parseNumber(swap.amount1)
      const amountUsd = parseNumber(swap.amountUSD)
      const contentInToken0 = swap.token0.id.toLowerCase() === contentAddressLower
      const contentAmount = contentInToken0 ? amount0 : amount1
      const side = contentAmount < 0 ? 'Buy' : contentAmount > 0 ? 'Sell' : 'Swap'
      const wallet = swap.origin || swap.sender
      const ts = parseNumber(swap.timestamp || swap.transaction?.timestamp || 0)
      return {
        id: swap.id,
        timestamp: ts,
        side,
        amountUsd,
        amount0,
        amount1,
        token0Address: swap.token0.id,
        token1Address: swap.token1.id,
        token0Symbol: swap.token0.symbol || 'TOKEN0',
        token1Symbol: swap.token1.symbol || 'TOKEN1',
        wallet,
        txHash: swap.transaction?.id ?? '',
      }
    })
  }, [swaps, contentCoinAddress])

  const creatorHandle = coin?.creatorProfile?.handle
  const creatorAddress = coin?.creatorAddress || coin?.payoutRecipientAddress
  const creatorProfileIdentifier = creatorHandle || creatorAddress
  const { data: creatorProfile } = useZoraProfile(creatorProfileIdentifier)
  const { theme: ethosTheme } = useCreatorEthosPageTheme({
    profile: creatorProfile ?? null,
    creatorAddress: creatorAddress ?? null,
    serverEthosScore: coin?.ethosScore,
    serverEthosLevel: coin?.ethosLevel,
  })

  if (!chain || !isSupportedExploreChain(chain)) {
    return <Navigate replace to="/explore/content" />
  }

  if (!contentCoinAddress) {
    return <Navigate replace to="/explore/content" />
  }

  const shortAddress = (addr: string) => formatShortAddress(addr, '')

  const symbol = coin?.symbol || 'CONTENT'
  const name = coin?.name || 'Content Coin'
  const mediaUrl = toDisplayAssetUrl(coin?.mediaContent?.previewImage?.medium || coin?.mediaContent?.originalUri)
  const creatorCoinAddress = isAddress(creatorProfile?.creatorCoin?.address || '')
    ? getAddress(creatorProfile?.creatorCoin?.address as `0x${string}`)
    : null
  const creatorDetailPath = creatorCoinAddress
    ? `/explore/creators/${chain.toLowerCase()}/${creatorCoinAddress}`
    : null
  const creatorFallbackPath = '/deploy/coin'
  const creatorBreadcrumbLabel = creatorHandle ? `@${creatorHandle}` : 'Creator'
  const contentBreadcrumbLabel = name
  const description = coin?.description?.trim() || 'A content coin deployed on Zora and traded with 4626 liquidity routing.'
  const holdersCount = parseNumber(coin?.uniqueHolders)
  const totalSupplyCount = parseNumber(coin?.totalSupply)
  const marketCapUsd = parseNumber(coin?.marketCap)
  const createdLabel = formatDateLabel(coin?.createdAt)
  const canonicalPath = `/explore/content/${chain.toLowerCase()}/${contentCoinAddress}`

  const compactContentSymbol = symbol.length > 18 ? `${symbol.slice(0, 15)}…` : symbol
  const swapUrl = `/swap?token=${contentCoinAddress}`
  const liquidityUrl = primaryPool?.id
    ? `https://app.uniswap.org/explore/pools/base/${primaryPool.id}`
    : `https://app.uniswap.org/explore/tokens/base/${contentCoinAddress}`
  const tvlUsd = history?.tvlUSD ?? parseNumber(primaryPool?.totalValueLockedUSD) ?? parseNumber(coin?.marketCap)
  const volumeUsd = history?.volumeUSD ?? parseNumber(coin?.volume24h)
  const feesUsd = history?.feesUSD
  const priceUsd = parseNumber(coin?.tokenPrice?.priceInUsdc)
  const priceDelta = history?.priceChangePercent ?? parseNumber(coin?.marketCapDelta24h)

  const points = history?.dataPoints ?? []

  const liquidityCV = calcCoefficientOfVariation(points.map((p) => p.tvlUSD))
  const priceCV = calcCoefficientOfVariation(points.map((p) => p.close ?? 0))

  const loading = coinLoading || poolsLoading

  return (
    <div className="relative min-h-0 w-full overflow-hidden bg-transparent">
      <EthosPageAmbience theme={ethosTheme} />
      <PageMeta
        title={`${name} (${symbol})`}
        description={description}
        canonicalPath={canonicalPath}
        ogImage={mediaUrl}
      />
      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 py-6">
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mb-4">
          <nav aria-label="Breadcrumb" className="inline-flex items-center gap-2 text-sm">
            <Link to="/explore" className="text-zinc-400 hover:text-white transition-colors">
              Explore
            </Link>
            <span className="text-zinc-600">→</span>
            {creatorDetailPath ? (
              <Link
                to={creatorDetailPath}
                className={cn(
                  'transition-colors',
                  ethosTheme.isActive ? ethosTheme.accentTextClass : 'text-zinc-400 hover:text-white',
                )}
              >
                {creatorBreadcrumbLabel}
              </Link>
            ) : (
              <Link to={creatorFallbackPath} className="text-zinc-400 hover:text-white transition-colors">
                {creatorBreadcrumbLabel}
              </Link>
            )}
            <span className="text-zinc-600">→</span>
            <span className="text-zinc-200">{contentBreadcrumbLabel}</span>
          </nav>
        </motion.div>

        <div className="space-y-6">
          <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }}>
            <div className="grid grid-cols-1 md:grid-cols-[minmax(0,1fr)_260px] lg:grid-cols-[minmax(0,1fr)_280px] gap-4 items-stretch">
            <div
              className={cn(
                'rounded-3xl border overflow-hidden cursor-zoom-in',
                ethosTheme.cardBorderClass,
                ethosTheme.cardSurfaceClass,
              )}
              role={mediaUrl ? 'button' : undefined}
              tabIndex={mediaUrl ? 0 : -1}
              onClick={() => {
                if (mediaUrl) setIsImageLightboxOpen(true)
              }}
              onKeyDown={(event) => {
                if (!mediaUrl) return
                if (event.key === 'Enter' || event.key === ' ') {
                  event.preventDefault()
                  setIsImageLightboxOpen(true)
                }
              }}
              aria-label={mediaUrl ? 'Open content image' : undefined}
            >
              <div className="relative px-4 py-6 sm:px-7 sm:py-7">
                {mediaUrl ? (
                  <>
                    <img
                      src={mediaUrl}
                      alt={name}
                      className="absolute inset-0 w-full h-full object-cover opacity-18 pointer-events-none"
                    />
                    <div className="absolute inset-0 bg-gradient-to-br from-black/85 via-black/70 to-zinc-900/90 pointer-events-none" />
                    {ethosTheme.isActive ? (
                      <div
                        className="absolute inset-0 pointer-events-none"
                        style={{
                          background: `linear-gradient(135deg, rgba(0,0,0,0.55) 0%, rgba(0,0,0,0.72) 50%, ${ethosTheme.accentHex}30 100%)`,
                        }}
                      />
                    ) : null}
                  </>
                ) : null}
                <EthosBlurOrbs theme={ethosTheme} className="blur-3xl" />

                <div className="relative">
                  <div className="flex items-center justify-between gap-3 flex-wrap mb-4">
                    <span className="inline-flex items-center gap-2 rounded-full border border-zinc-700/80 bg-vault-card/70 px-2.5 py-1 text-[11px] font-medium text-zinc-200">
                      <a
                        href={`https://zora.co/coin/base:${contentCoinAddress}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-2 hover:text-white transition-colors"
                        onClick={(event) => event.stopPropagation()}
                      >
                        <img src={ZORA_TOKEN_LOGO_URL} alt="Zora" className="h-3.5 w-3.5 object-contain" />
                        <span>Zora</span>
                        <span className="text-zinc-500">{shortAddress(contentCoinAddress)}</span>
                      </a>
                      <ExploreCopyButton
                        text={contentCoinAddress}
                        className="p-0"
                        iconClassName="w-3.5 h-3.5"
                        copiedIconClassName="w-3.5 h-3.5 text-emerald-400"
                        title="Copy content token address"
                      />
                      <a
                        href={`https://basescan.org/token/${contentCoinAddress}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center text-zinc-400 hover:text-white transition-colors"
                        onClick={(event) => event.stopPropagation()}
                        title="View on Basescan"
                      >
                        <img src={BASESCAN_ICON_URL} alt="Basescan" className="h-3.5 w-3.5 object-contain" />
                      </a>
                    </span>
                  </div>

                  <div className="flex items-center gap-4 mb-5">
                    {mediaUrl ? (
                      <img src={mediaUrl} alt={name} className="w-14 h-14 rounded-2xl object-cover border border-zinc-700/80 shadow-[0_0_0_1px_rgba(0,0,0,0.35)]" />
                    ) : (
                      <div className="w-14 h-14 rounded-2xl border border-zinc-700 bg-white/8 flex items-center justify-center text-sm text-zinc-300">
                        {symbol.slice(0, 2)}
                      </div>
                    )}
                    <div className="min-w-0">
                      <h2 className="text-2xl sm:text-4xl text-white font-semibold tracking-tight truncate">{name}</h2>
                      <div className="mt-1 flex items-center gap-2 text-sm text-zinc-300">
                        <span className="text-zinc-200">{symbol}</span>
                        <span className="text-zinc-600">•</span>
                        <span
                          className={cn(
                            'inline-flex items-center rounded-full px-2 py-0.5 text-xs border',
                            ethosTheme.isActive
                              ? cn(ethosTheme.cardSurfaceClass, ethosTheme.cardBorderClass, ethosTheme.accentTextClass)
                              : 'bg-white/8 text-zinc-300 border-zinc-700/80',
                          )}
                        >
                          {creatorHandle ? `@${creatorHandle}` : 'Unknown creator'}
                          {ethosTheme.isActive ? ` · ${ethosTheme.levelLabel}` : ''}
                        </span>
                        {typeof creatorAddress === 'string' && /^0x[a-fA-F0-9]{40}$/.test(creatorAddress) ? (
                          <ExploreEthosRefreshButton creatorAddress={creatorAddress} />
                        ) : null}
                      </div>
                    </div>
                  </div>

                  <p className="text-sm sm:text-[15px] text-zinc-300/95 leading-relaxed max-w-3xl">{description}</p>

                  <div className="mt-5 grid grid-cols-2 sm:grid-cols-4 gap-2.5">
                    <div className="rounded-2xl bg-vault-card/60/70 p-3">
                      <div className="text-[11px] font-medium text-zinc-500">Market Cap</div>
                      <div className="text-[15px] text-white mt-1.5 tabular-nums">{formatUsd(marketCapUsd)}</div>
                    </div>
                    <div className="rounded-2xl bg-vault-card/60/70 p-3">
                      <div className="text-[11px] font-medium text-zinc-500">Holders</div>
                      <div className="text-[15px] text-white mt-1.5 tabular-nums">{formatCount(holdersCount)}</div>
                    </div>
                    <div className="rounded-2xl bg-vault-card/60/70 p-3">
                      <div className="text-[11px] font-medium text-zinc-500">Supply</div>
                      <div className="text-[15px] text-white mt-1.5 tabular-nums">{formatSupply(totalSupplyCount)}</div>
                    </div>
                    <div className="rounded-2xl bg-vault-card/60/70 p-3">
                      <div className="text-[11px] font-medium text-zinc-500">Created</div>
                      <div className="text-[15px] text-white mt-1.5 tabular-nums">{createdLabel}</div>
                    </div>
                  </div>

                  <div className="mt-4 flex flex-wrap items-center gap-2.5 text-xs">
                    <button
                      type="button"
                      className={cn(
                        'inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-white transition-colors',
                        ethosTheme.isActive ? ethosTheme.primaryCtaHoverClass : 'bg-fuchsia-600 hover:bg-fuchsia-500',
                      )}
                      style={ethosTheme.isActive ? ethosTheme.primaryCtaStyle : undefined}
                      onClick={(event) => {
                        event.stopPropagation()
                        setIsSwapTrayOpen(true)
                      }}
                    >
                      <span aria-hidden="true" className="text-zinc-400">▤</span>
                      Swap
                    </button>
                    <a
                      href={liquidityUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-2 rounded-full bg-white/8 px-3 py-1.5 text-zinc-200 hover:bg-white/12 transition-colors"
                      onClick={(event) => event.stopPropagation()}
                    >
                      <img src={UNISWAP_ICON_URL} alt="Uniswap" className="h-3.5 w-3.5 object-contain" />
                      Add liquidity
                    </a>
                  </div>
                </div>
              </div>
            </div>

            <div
              className={cn(
                'h-full rounded-2xl border p-4 sm:p-5',
                ethosTheme.isActive ? cn(ethosTheme.cardBorderClass, ethosTheme.cardSurfaceClass) : 'border-white/8 bg-white/3',
              )}
            >
              <div className="flex items-center justify-between mb-3">
                <div className="text-xs font-medium text-zinc-500">Pool Snapshot</div>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    className="text-zinc-400 hover:text-white transition-colors"
                    title="Share"
                    onClick={async () => {
                      await navigator.clipboard.writeText(window.location.href)
                    }}
                  >
                    <Share2 className="w-4 h-4" />
                  </button>
                </div>
              </div>

              <div className="grid grid-cols-1">
                <ExploreStatRow
                  label={renderSnapshotLabel('TVL', SNAPSHOT_METRIC_HELP.tvl)}
                  value={formatUsd(tvlUsd)}
                  rowClassName="py-2 border-b border-white/8 last:border-0"
                />
                <ExploreStatRow
                  label={renderSnapshotLabel(`Volume (${selectedPeriod})`, SNAPSHOT_METRIC_HELP.volume)}
                  value={formatUsd(volumeUsd)}
                  rowClassName="py-2 border-b border-white/8 last:border-0"
                />
                <ExploreStatRow
                  label={renderSnapshotLabel(`Fees (${selectedPeriod})`, SNAPSHOT_METRIC_HELP.fees)}
                  value={formatUsd(feesUsd ?? 0)}
                  rowClassName="py-2 border-b border-white/8 last:border-0"
                />
                <ExploreStatRow
                  label={renderSnapshotLabel('Token Price', SNAPSHOT_METRIC_HELP.tokenPrice)}
                  value={formatTokenPrice(priceUsd)}
                  rowClassName="py-2 border-b border-white/8 last:border-0"
                />
                <ExploreStatRow
                  label={renderSnapshotLabel('Price Change', SNAPSHOT_METRIC_HELP.priceChange)}
                  value={formatPercent(priceDelta)}
                  rowClassName="py-2 border-b border-white/8 last:border-0"
                />
                <ExploreStatRow
                  label={renderSnapshotLabel('Liquidity Variance', SNAPSHOT_METRIC_HELP.liquidityVariance)}
                  value={liquidityCV == null ? '-' : `${liquidityCV.toFixed(2)}% CV`}
                  rowClassName="py-2 border-b border-white/8 last:border-0"
                />
                <ExploreStatRow
                  label={renderSnapshotLabel('Price Variance', SNAPSHOT_METRIC_HELP.priceVariance)}
                  value={priceCV == null ? '-' : `${priceCV.toFixed(2)}% CV`}
                  rowClassName="py-2 border-b border-white/8 last:border-0"
                />
              </div>
            </div>
            </div>

            <div
              className={cn(
                'mt-6 rounded-2xl border p-4 sm:p-5',
                ethosTheme.isActive ? cn(ethosTheme.cardBorderClass, ethosTheme.cardSurfaceClass) : 'border-white/8 bg-white/3',
              )}
            >
              <div className="flex flex-wrap items-center justify-between gap-3 mb-4">
                <div className="flex items-center gap-1.5 overflow-x-auto w-full sm:w-auto pb-1">
                  {PERIODS.map((period) => (
                    <button
                      key={period}
                      type="button"
                      onClick={() => setSelectedPeriod(period)}
                      className={`px-3 py-1.5 rounded-full text-[11px] font-medium whitespace-nowrap transition-colors ${
                        selectedPeriod === period
                          ? 'bg-zinc-700 text-white'
                          : 'text-zinc-500 hover:text-white hover:bg-white/8'
                      }`}
                    >
                      {period}
                    </button>
                  ))}
                </div>

                <div className="flex items-center gap-1.5 overflow-x-auto w-full sm:w-auto pb-1">
                  {METRICS.map((m) => {
                    const on = selectedMetric === m.key
                    const color = METRIC_COLORS[m.key].primary
                    return (
                      <button
                        key={m.key}
                        type="button"
                        onClick={() => setSelectedMetric(m.key)}
                        aria-pressed={on}
                        className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[11px] font-medium whitespace-nowrap transition-all border ${
                          on
                            ? 'border-white/10 bg-white/[0.06] text-white'
                            : 'border-white/5 bg-transparent text-zinc-600 hover:text-zinc-300 hover:bg-white/[0.04]'
                        }`}
                        style={on ? { boxShadow: `inset 0 0 0 1px ${color}40` } : undefined}
                      >
                        <span
                          className="inline-block h-1.5 w-1.5 shrink-0 rounded-full"
                          style={{
                            background: on ? color : 'transparent',
                            border: `1px solid ${on ? color : 'rgba(255,255,255,0.15)'}`,
                          }}
                          aria-hidden="true"
                        />
                        {m.icon}
                        <span className="hidden sm:inline">{m.label}</span>
                      </button>
                    )
                  })}
                </div>
              </div>

              {loading || historyLoading ? (
                <LoadingBlock intent="processing" minHeightClassName="h-[420px]" className="rounded-xl bg-white/4" />
              ) : (
                <MetricChart
                  points={points}
                  metric={selectedMetric}
                  pool={history?.pool ?? null}
                  period={selectedPeriod}
                />
              )}

              <div className="mt-3 flex items-center justify-between text-xs text-zinc-500">
                <span>Oldest</span>
                <span className="text-zinc-400">
                  {METRICS.find((m) => m.key === selectedMetric)?.label}
                  {selectedMetric === 'fees' ? ' (cumulative)' : ''} over {selectedPeriod}
                </span>
                <span>Latest</span>
              </div>
            </div>

            <div
              className={cn(
                'mt-6 rounded-2xl border overflow-hidden',
                ethosTheme.isActive ? cn(ethosTheme.cardBorderClass, ethosTheme.cardSurfaceClass) : 'border-white/8 bg-white/3',
              )}
            >
              <div className="px-4 py-3 border-b border-white/8 flex items-center justify-between">
                <div>
                  <div className="text-sm text-white font-medium">Recent Activity</div>
                  <div className="text-xs text-zinc-500">Latest swaps from the primary pool</div>
                </div>
                <Link
                  to={`/explore/content/${chain.toLowerCase()}/${contentCoinAddress}/transactions`}
                  className="text-xs text-zinc-400 hover:text-white"
                >
                  Full transactions
                </Link>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full min-w-[640px] text-sm">
                  <thead className="bg-vault-card/60/70">
                    <tr className="text-left text-zinc-500 text-xs font-medium">
                      <th className="px-4 py-3">Time</th>
                      <th className="px-4 py-3">Type</th>
                      <th className="px-4 py-3 text-right">USD</th>
                      <th className="px-4 py-3 text-right">
                        <PoolTokenHeader
                          address={primaryPool?.token0.id}
                          symbol={primaryPool?.token0.symbol ?? 'Token0'}
                        />
                      </th>
                      <th className="px-4 py-3 text-right">
                        <PoolTokenHeader
                          address={primaryPool?.token1.id}
                          symbol={primaryPool?.token1.symbol ?? 'Token1'}
                        />
                      </th>
                      <th className="px-4 py-3 text-right">Wallet</th>
                    </tr>
                  </thead>
                  <tbody>
                    {swapsLoading ? (
                      <tr>
                        <td colSpan={6} className="px-4 py-8 text-center text-zinc-600">
                          <LoadingText intent="processing" labelOverride="Loading swaps..." />
                        </td>
                      </tr>
                    ) : activityRows.length === 0 ? (
                      <tr>
                        <td colSpan={6} className="px-4 py-8 text-center text-zinc-600">
                          No swap data available for this pool yet.
                        </td>
                      </tr>
                    ) : (
                      activityRows.map((row) => (
                        <tr key={row.id} className="border-t border-white/8/70">
                          <td className="px-4 py-3 text-zinc-400">{formatTimestamp(row.timestamp)}</td>
                          <td className="px-4 py-3">
                            <span
                              className={`inline-flex rounded-full px-2 py-0.5 text-xs font-medium ${
                                row.side === 'Buy'
                                  ? 'bg-emerald-500/15 text-emerald-300'
                                  : row.side === 'Sell'
                                    ? 'bg-rose-500/15 text-rose-300'
                                    : 'bg-zinc-600/25 text-zinc-300'
                              }`}
                            >
                              {row.side}
                            </span>
                          </td>
                          <td className="px-4 py-3 text-right text-white tabular-nums">{formatUsd(row.amountUsd)}</td>
                          <td className="px-4 py-3 text-right text-zinc-300 tabular-nums">
                            <span className="inline-flex items-center justify-end gap-2">
                              <span>{formatTokenAmount(row.amount0)}</span>
                              <TokenAvatar
                                token={{ address: row.token0Address, symbol: row.token0Symbol, chainId: 8453 }}
                                symbol={row.token0Symbol}
                                size={16}
                                className="shrink-0"
                                withFallbackLabel
                              />
                            </span>
                          </td>
                          <td className="px-4 py-3 text-right text-zinc-300 tabular-nums">
                            <span className="inline-flex items-center justify-end gap-2">
                              <span>{formatTokenAmount(row.amount1)}</span>
                              <TokenAvatar
                                token={{ address: row.token1Address, symbol: row.token1Symbol, chainId: 8453 }}
                                symbol={row.token1Symbol}
                                size={16}
                                className="shrink-0"
                                withFallbackLabel
                              />
                            </span>
                          </td>
                          <td className="px-4 py-3 text-right">
                            <WalletIdentityCell wallet={row.wallet} txHash={row.txHash} />
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
      {isSwapTrayOpen ? (
        <div className="fixed inset-0 z-[145]">
          <button
            type="button"
            className="absolute inset-0 bg-black/55 backdrop-blur-[1px]"
            onClick={() => setIsSwapTrayOpen(false)}
            aria-label="Close swap tray"
          />
          <aside className="absolute right-0 top-0 hidden h-full w-full max-w-[380px] border-l border-white/10 bg-black/95 p-5 sm:block">
            <div className="flex items-center justify-between">
              <div className="text-sm font-medium text-white">Swap {compactContentSymbol}</div>
              <button
                type="button"
                onClick={() => setIsSwapTrayOpen(false)}
                className="inline-flex h-8 w-8 items-center justify-center text-zinc-400 hover:text-white"
                aria-label="Close tray"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
            <div className="mt-4 space-y-2 text-sm">
              <Link
                to={swapUrl}
                className="inline-flex w-full items-center justify-between gap-2 rounded-xl border border-white/10 bg-white/6 px-3 py-2 text-zinc-200 hover:bg-white/10"
                onClick={() => setIsSwapTrayOpen(false)}
              >
                <span className="inline-flex items-center gap-2">
                  <img src={UNISWAP_ICON_URL} alt="Uniswap" className="h-4 w-4 object-contain" />
                  Open in 4626 Swap
                </span>
                <ExternalLink className="h-4 w-4" />
              </Link>
              <a
                href={`https://app.uniswap.org/explore/tokens/base/${contentCoinAddress}`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex w-full items-center justify-between gap-2 rounded-xl border border-white/10 bg-white/6 px-3 py-2 text-zinc-200 hover:bg-white/10"
                onClick={() => setIsSwapTrayOpen(false)}
              >
                <span className="inline-flex items-center gap-2">
                  <img src={UNISWAP_ICON_URL} alt="Uniswap" className="h-4 w-4 object-contain" />
                  Open in Uniswap
                </span>
                <ExternalLink className="h-4 w-4" />
              </a>
            </div>
          </aside>
          <aside className="absolute bottom-0 left-0 right-0 rounded-t-2xl border-t border-white/10 bg-black/95 p-5 sm:hidden">
            <div className="flex items-center justify-between">
              <div className="text-sm font-medium text-white">Swap {compactContentSymbol}</div>
              <button
                type="button"
                onClick={() => setIsSwapTrayOpen(false)}
                className="inline-flex h-8 w-8 items-center justify-center text-zinc-400 hover:text-white"
                aria-label="Close tray"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
            <div className="mt-4 space-y-2 text-sm">
              <Link
                to={swapUrl}
                className="inline-flex w-full items-center justify-between gap-2 rounded-xl border border-white/10 bg-white/6 px-3 py-2 text-zinc-200 hover:bg-white/10"
                onClick={() => setIsSwapTrayOpen(false)}
              >
                <span className="inline-flex items-center gap-2">
                  <img src={UNISWAP_ICON_URL} alt="Uniswap" className="h-4 w-4 object-contain" />
                  Open in 4626 Swap
                </span>
                <ExternalLink className="h-4 w-4" />
              </Link>
              <a
                href={`https://app.uniswap.org/explore/tokens/base/${contentCoinAddress}`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex w-full items-center justify-between gap-2 rounded-xl border border-white/10 bg-white/6 px-3 py-2 text-zinc-200 hover:bg-white/10"
                onClick={() => setIsSwapTrayOpen(false)}
              >
                <span className="inline-flex items-center gap-2">
                  <img src={UNISWAP_ICON_URL} alt="Uniswap" className="h-4 w-4 object-contain" />
                  Open in Uniswap
                </span>
                <ExternalLink className="h-4 w-4" />
              </a>
            </div>
          </aside>
        </div>
      ) : null}
      {mediaUrl && isImageLightboxOpen ? (
        <div className="fixed inset-0 z-[140]">
          <button
            type="button"
            className="absolute inset-0 bg-black/80 backdrop-blur-[1px]"
            onClick={() => setIsImageLightboxOpen(false)}
            aria-label="Close image preview"
          />
          <div className="absolute inset-0 flex items-center justify-center p-4 sm:p-8">
            <button
              type="button"
              onClick={() => setIsImageLightboxOpen(false)}
              className="absolute right-4 top-4 z-10 inline-flex h-9 w-9 items-center justify-center rounded-full bg-black/65 text-zinc-200 hover:text-white hover:bg-black/80 transition-colors"
              aria-label="Close image preview"
              title="Close"
            >
              <X className="h-4 w-4" />
            </button>
            <img
              src={mediaUrl}
              alt={name}
              className="max-h-[92vh] max-w-[92vw] rounded-xl object-contain shadow-[0_20px_80px_rgba(0,0,0,0.6)]"
            />
          </div>
        </div>
      ) : null}
    </div>
  )
}
