begin;

drop index if exists public.referral_clicks_referrer_created_idx;
drop index if exists public.referral_clicks_code_created_idx;
drop index if exists public.referral_conversions_code_created_idx;
drop index if exists public.idx_creator_allowlist_address;
drop index if exists public.creator_access_requests_status_created_idx;
drop index if exists public.agent_api_logs_endpoint_idx;
drop index if exists public.creator_agent_wallets_address_idx;
drop index if exists public.idx_creator_access_requests_status;
drop index if exists public.admin_logs_admin_idx;
drop index if exists public.admin_logs_action_idx;
drop index if exists public.admin_logs_target_idx;
drop index if exists public.creator_allowlist_csw_idx;
drop index if exists public.profile_wallets_address_idx;
drop index if exists public.wallets_type_idx;
drop index if exists public.profiles_primary_smart_wallet_idx;
drop index if exists public.agent_rate_limits_key_idx;
drop index if exists public.creator_xmtp_agents_listed_idx;
drop index if exists public.creator_allowlist_active_address_idx;
drop index if exists public.keepr_actions_dedupe_idx;
drop index if exists public.keepr_join_requests_status_idx;
drop index if exists public.keepr_join_requests_vault_wallet_idx;
drop index if exists public.keepr_vaults_owner_idx;
drop index if exists public.keepr_nonces_wallet_idx;
drop index if exists public.keepr_nonces_expires_idx;
drop index if exists public.keepr_actions_group_idx;
drop index if exists public.keepr_audit_vault_idx;
drop index if exists public.deploy_sessions_sender_idx;
drop index if exists public.deploy_sessions_step_idx;
drop index if exists public.deploy_sessions_expires_idx;
drop index if exists public.keepr_vaults_lens_group_idx;
drop index if exists public.agent_subdomains_owner_idx;
drop index if exists public.agent_subdomains_lens_owner_idx;
drop index if exists public.agent_subdomains_updated_idx;
drop index if exists public.creator_coins_last_seen_idx;
drop index if exists public.creators_first_seen_idx;

commit;;
