-- Data-driven AlfaClub room channel registry and durable cross-channel ingress.
-- Server-only foundation: this migration does not enable any relay by itself.

BEGIN;

CREATE SCHEMA IF NOT EXISTS alfaclub;

CREATE TABLE IF NOT EXISTS alfaclub.room_channel_bindings (
  room_id                      TEXT PRIMARY KEY,
  enabled                      BOOLEAN NOT NULL DEFAULT FALSE,
  rollout_status               TEXT NOT NULL DEFAULT 'disabled',
  telegram_enabled             BOOLEAN NOT NULL DEFAULT FALSE,
  telegram_chat_id             TEXT,
  telegram_thread_id           TEXT,
  xmtp_enabled                 BOOLEAN NOT NULL DEFAULT FALSE,
  xmtp_group_id                TEXT,
  synthetic_keepr_vault_address TEXT,
  created_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT room_channel_bindings_room_id_check
    CHECK (length(btrim(room_id)) BETWEEN 1 AND 128),
  CONSTRAINT room_channel_bindings_rollout_status_check
    CHECK (rollout_status IN ('disabled', 'canary', 'enabled')),
  CONSTRAINT room_channel_bindings_telegram_config_check
    CHECK (NOT telegram_enabled OR telegram_chat_id IS NOT NULL),
  CONSTRAINT room_channel_bindings_xmtp_config_check
    CHECK (NOT xmtp_enabled OR synthetic_keepr_vault_address IS NOT NULL),
  CONSTRAINT room_channel_bindings_synthetic_vault_check
    CHECK (
      synthetic_keepr_vault_address IS NULL
      OR synthetic_keepr_vault_address ~ '^0x[0-9a-f]{40}$'
    )
);

CREATE INDEX IF NOT EXISTS room_channel_bindings_rollout_idx
  ON alfaclub.room_channel_bindings (enabled, rollout_status, room_id);

CREATE TABLE IF NOT EXISTS alfaclub.cross_channel_ingress (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_channel        TEXT NOT NULL,
  source_message_id     TEXT NOT NULL,
  source_conversation_id TEXT,
  target_room_id        TEXT NOT NULL,
  original_text         TEXT NOT NULL,
  alfaclub_room_id      TEXT,
  alfaclub_message_id   TEXT,
  validated_profile_id  BIGINT,
  validated_issuer      TEXT,
  claimed_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  linked_at             TIMESTAMPTZ,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT cross_channel_ingress_source_channel_check
    CHECK (source_channel IN ('telegram', 'xmtp', 'web4626')),
  CONSTRAINT cross_channel_ingress_source_message_id_check
    CHECK (length(btrim(source_message_id)) BETWEEN 1 AND 512),
  CONSTRAINT cross_channel_ingress_target_room_id_check
    CHECK (length(btrim(target_room_id)) BETWEEN 1 AND 128),
  CONSTRAINT cross_channel_ingress_original_text_check
    CHECK (length(original_text) <= 20000),
  CONSTRAINT cross_channel_ingress_validated_profile_check
    CHECK (validated_profile_id IS NULL OR validated_profile_id > 0),
  CONSTRAINT cross_channel_ingress_validated_issuer_check
    CHECK (
      validated_issuer IS NULL
      OR length(btrim(validated_issuer)) BETWEEN 1 AND 256
    ),
  CONSTRAINT cross_channel_ingress_link_pair_check
    CHECK (
      (alfaclub_room_id IS NULL AND alfaclub_message_id IS NULL)
      OR (alfaclub_room_id IS NOT NULL AND alfaclub_message_id IS NOT NULL)
    ),
  CONSTRAINT cross_channel_ingress_validation_pair_check
    CHECK (
      (validated_profile_id IS NULL AND validated_issuer IS NULL)
      OR (validated_profile_id IS NOT NULL AND validated_issuer IS NOT NULL)
    ),
  CONSTRAINT cross_channel_ingress_linked_at_check
    CHECK (
      linked_at IS NULL
      OR (
        alfaclub_room_id IS NOT NULL
        AND alfaclub_message_id IS NOT NULL
        AND validated_profile_id IS NOT NULL
        AND validated_issuer IS NOT NULL
      )
    ),
  UNIQUE (source_channel, source_message_id)
);

CREATE INDEX IF NOT EXISTS cross_channel_ingress_target_room_idx
  ON alfaclub.cross_channel_ingress (target_room_id, claimed_at DESC);

CREATE INDEX IF NOT EXISTS cross_channel_ingress_profile_idx
  ON alfaclub.cross_channel_ingress (validated_profile_id, linked_at DESC)
  WHERE validated_profile_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS cross_channel_ingress_alfaclub_message_idx
  ON alfaclub.cross_channel_ingress (alfaclub_room_id, alfaclub_message_id)
  WHERE alfaclub_room_id IS NOT NULL AND alfaclub_message_id IS NOT NULL;

ALTER TABLE alfaclub.room_channel_bindings ENABLE ROW LEVEL SECURITY;
ALTER TABLE alfaclub.cross_channel_ingress ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS deny_public_rest ON alfaclub.room_channel_bindings;
CREATE POLICY deny_public_rest ON alfaclub.room_channel_bindings
  AS RESTRICTIVE FOR ALL TO public USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS deny_public_rest ON alfaclub.cross_channel_ingress;
CREATE POLICY deny_public_rest ON alfaclub.cross_channel_ingress
  AS RESTRICTIVE FOR ALL TO public USING (false) WITH CHECK (false);

REVOKE ALL PRIVILEGES ON TABLE alfaclub.room_channel_bindings
  FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE alfaclub.cross_channel_ingress
  FROM PUBLIC, anon, authenticated;
GRANT ALL PRIVILEGES ON TABLE alfaclub.room_channel_bindings TO service_role;
GRANT ALL PRIVILEGES ON TABLE alfaclub.cross_channel_ingress TO service_role;
GRANT USAGE, SELECT ON SEQUENCE alfaclub.cross_channel_ingress_id_seq TO service_role;

INSERT INTO alfaclub.room_channel_bindings (
  room_id,
  enabled,
  rollout_status,
  telegram_enabled,
  xmtp_enabled,
  synthetic_keepr_vault_address
) VALUES (
  '1659',
  FALSE,
  'canary',
  FALSE,
  FALSE,
  '0x0000000000000000000000000000000000001659'
)
ON CONFLICT (room_id) DO NOTHING;

ALTER TABLE alfaclub.chat_bridge_message_origin
  DROP CONSTRAINT IF EXISTS chat_bridge_message_origin_origin_check;
ALTER TABLE alfaclub.chat_bridge_message_origin
  ADD CONSTRAINT chat_bridge_message_origin_origin_check
  CHECK (origin IN ('telegram', 'xmtp', 'web4626')) NOT VALID;
ALTER TABLE alfaclub.chat_bridge_message_origin
  VALIDATE CONSTRAINT chat_bridge_message_origin_origin_check;

COMMENT ON TABLE alfaclub.room_channel_bindings IS
  'Server-only room channel registry. Rows are inert unless enabled and promoted through rollout_status.';
COMMENT ON COLUMN alfaclub.room_channel_bindings.synthetic_keepr_vault_address IS
  'Synthetic routing identity only; it does not select custody, a signer, or an execution wallet.';
COMMENT ON TABLE alfaclub.cross_channel_ingress IS
  'Idempotent source-message claims and links to validated AlfaClub room messages and issuer profiles.';
COMMENT ON COLUMN alfaclub.cross_channel_ingress.validated_issuer IS
  'Canonical CSW validated for the linked profile and external channel at ingress time.';
COMMENT ON COLUMN alfaclub.cross_channel_ingress.original_text IS
  'Bounded original external message text used for authenticated command execution.';
COMMENT ON TABLE alfaclub.chat_bridge_message_origin IS
  'Tags AlfaClub room messages posted by telegram, XMTP, or 4626 web ingress so outbound fan-out can skip self-echo.';

COMMIT;
